import { createContext, useContext, useState, useEffect } from 'react';

// ============================================================
// COMPLETE TRANSLATIONS — all UI text in all 7 NER languages
// ============================================================
const TRANSLATIONS = {
  en: {
    appName: 'CogniCare NER',
    tagline: 'Memory Care Platform',
    patient: 'Patient',
    caregiver: 'Caregiver',
    games: 'Cognitive Games',
    reminders: 'Daily Reminders',
    dashboard: 'Dashboard',
    patients: 'Patient Profiles',
    alerts: 'Alerts & Insights',
    settings: 'Settings',
    back: 'Back',
    next: 'Next',
    play: 'Play',
    score: 'Score',
    level: 'Level',
    correct: 'Well done! That is correct!',
    tryAgain: 'Almost! Try once more.',
    gameComplete: 'Wonderful! You completed the exercise!',
    medicine: 'Medicine Reminder',
    water: 'Drink Water',
    exercise: 'Light Exercise',
    appointment: 'Doctor Appointment',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    selectLanguage: 'Language',
    selectTheme: 'Theme',
    switchPortal: 'Switch Portal',
    patientPortal: 'Patient Portal',
    caregiverPortal: 'Caregiver Portal',
    gamesSubtitle: 'Choose an exercise to begin. Each game trains a different part of your mind.',
    readAloud: 'Read Aloud',
    gamesAvailable: 'Games Available',
    gamesPlayed: 'Games Played',
    overallAccuracy: 'Overall Accuracy',
    welcome: 'Welcome to CogniCare NER',
    heroSubtitle: 'AI-powered cognitive gaming and memory assistance for elderly dementia patients across India\'s North Eastern Region.',
    enterPatient: 'Enter Patient Portal',
    enterCaregiver: 'Enter Caregiver Portal',
    // Reminder labels
    morningMedicine: 'Morning Medicine',
    drinkWater: 'Drink Water',
    morningWalk: 'Morning Walk',
    brainGames: 'Brain Games Time',
    lunchMedicine: 'Lunch Medicine',
    afternoonRest: 'Rest & Nap',
    teaSnack: 'Tea & Snack',
    eveningWalk: 'Evening Walk',
    doctorAppointment: 'Doctor Appointment',
    eveningMedicine: 'Evening Medicine',
    musicTherapy: 'Music Therapy',
    sleepPrep: 'Sleep Preparation',
    // Reminder details
    morningMedicineDetail: 'Take prescribed morning tablets with warm water',
    drinkWaterDetail: 'Have a glass of warm water — stay hydrated',
    morningWalkDetail: '15-minute gentle walk in the garden',
    brainGamesDetail: 'Play 2–3 cognitive exercises for mental stimulation',
    lunchMedicineDetail: 'Take prescribed afternoon tablets after lunch',
    afternoonRestDetail: 'Short 30-minute rest for recovery',
    teaSnackDetail: 'Enjoy Assam tea with light wholesome snacks',
    eveningWalkDetail: 'Short evening walk for fresh air',
    doctorAppointmentDetail: 'Weekly tele-consultation with neurologist',
    eveningMedicineDetail: 'Take prescribed evening tablets with dinner',
    musicTherapyDetail: 'Listen to calming NER folk music',
    sleepPrepDetail: 'Dim lights and prepare for restful sleep',
    // Progress / KPIs
    todayProgress: "Today's Daily Progress",
    currentTime: 'Current Time',
    overallProgress: 'Overall Progress',
    medicinesLabel: 'Medicines',
    hydrationLabel: 'Hydration',
    allTaken: 'All taken!',
    wellHydrated: 'Well hydrated!',
    drinkMoreWater: 'Drink more water',
    // Game titles
    memoryMatch: 'Landmark Memory',
    melodyMemory: 'Melody Memory',
    dailyRoutine: 'Daily Routine',
    marketSorting: 'Bazaar Sorting',
    patternReplication: 'Weaving Patterns',
    wordCompletion: 'Word Recall',
    numberPatterns: 'Number Patterns',
    culturalConnections: 'Cultural Connections',
    colourWord: 'Colour & Word',
    proverbCompletion: 'Proverb Wisdom',
  },

  as: { // Assamese
    appName: 'কগ্নিকেয়াৰ NER',
    tagline: 'স্মৃতি যত্ন মঞ্চ',
    patient: 'ৰোগী',
    caregiver: 'পৰিচৰ্যাকাৰী',
    games: 'জ্ঞানমূলক খেল',
    reminders: 'দৈনিক সোঁৱৰণী',
    dashboard: 'ডেছবোৰ্ড',
    patients: 'ৰোগীৰ তথ্য',
    alerts: 'সতৰ্কবাৰ্তা',
    settings: 'ছেটিং',
    back: 'পিছলৈ',
    next: 'পৰৱৰ্তী',
    play: 'খেলক',
    score: 'নম্বৰ',
    level: 'স্তৰ',
    correct: 'বঢ়িয়া! শুদ্ধ উত্তৰ!',
    tryAgain: 'প্ৰায় হৈছিল! আকৌ চেষ্টা কৰক।',
    gameComplete: 'অসাধাৰণ! আপুনি অনুশীলন সম্পূৰ্ণ কৰিলে!',
    medicine: 'ঔষধৰ সোঁৱৰণী',
    water: 'পানী খাওক',
    exercise: 'লঘু ব্যায়াম',
    appointment: 'চিকিৎসকৰ পৰামৰ্শ',
    morning: 'ৰাতিপুৱা',
    afternoon: 'দুপৰীয়া',
    evening: 'সন্ধিয়া',
    selectLanguage: 'ভাষা',
    selectTheme: 'থিম',
    switchPortal: 'পৰ্টেল সলনি',
    patientPortal: 'ৰোগী পৰ্টেল',
    caregiverPortal: 'পৰিচৰ্যাকাৰী পৰ্টেল',
    gamesSubtitle: 'এটা অনুশীলন বাছি লওক। প্ৰতিটো খেলে আপোনাৰ মনৰ বেলেগ অংশ প্ৰশিক্ষণ দিয়ে।',
    readAloud: 'জোৰেৰে পঢ়ক',
    gamesAvailable: 'খেল উপলব্ধ',
    gamesPlayed: 'খেল খেলিলে',
    overallAccuracy: 'সামগ্ৰিক নিখুঁততা',
    welcome: 'কগ্নিকেয়াৰ NER-লৈ স্বাগতম',
    heroSubtitle: 'উত্তৰ-পূব ভাৰতৰ বৃদ্ধ ডিমেনছিয়া ৰোগীসকলৰ বাবে AI-চালিত জ্ঞানমূলক খেল আৰু স্মৃতি সহায়তা।',
    enterPatient: 'ৰোগী পৰ্টেলত প্ৰৱেশ',
    enterCaregiver: 'পৰিচৰ্যাকাৰী পৰ্টেলত প্ৰৱেশ',
    morningMedicine: 'ৰাতিপুৱাৰ ঔষধ',
    drinkWater: 'পানী খাওক',
    morningWalk: 'ৰাতিপুৱাৰ খোজকঢ়া',
    brainGames: 'মগজুৰ খেলৰ সময়',
    lunchMedicine: 'দুপৰীয়াৰ ঔষধ',
    afternoonRest: 'জিৰণি আৰু টোপনি',
    teaSnack: 'চাহ আৰু জলপান',
    eveningWalk: 'সন্ধিয়াৰ খোজকঢ়া',
    doctorAppointment: 'চিকিৎসকৰ পৰামৰ্শ',
    eveningMedicine: 'সন্ধিয়াৰ ঔষধ',
    musicTherapy: 'সংগীত চিকিৎসা',
    sleepPrep: 'শোৱাৰ প্ৰস্তুতি',
    morningMedicineDetail: 'ৰাতিপুৱাৰ বড়িসমূহ গৰম পানীৰে খাওক',
    drinkWaterDetail: 'এগিলাচ গৰম পানী খাওক - জলযুক্ত থাকক',
    morningWalkDetail: 'বাগিচাত ১৫ মিনিট সহজে খোজকঢ়া',
    brainGamesDetail: 'মানসিক উদ্দীপনাৰ বাবে ২-৩টা খেল খেলক',
    lunchMedicineDetail: 'দুপৰীয়াৰ আহাৰৰ পিছত ঔষধ খাওক',
    afternoonRestDetail: 'পুনৰুদ্ধাৰৰ বাবে চুটি ৩০ মিনিটৰ জিৰণি',
    teaSnackDetail: 'অসমীয়া চাহ আৰু লঘু খাদ্য উপভোগ কৰক',
    eveningWalkDetail: 'তাজা বায়ুৰ বাবে চুটি সন্ধিয়াৰ খোজকঢ়া',
    doctorAppointmentDetail: 'স্নায়ু বিশেষজ্ঞৰ সৈতে সাপ্তাহিক টেলি-পৰামৰ্শ',
    eveningMedicineDetail: 'ৰাতিৰ আহাৰৰ সৈতে সন্ধিয়াৰ ঔষধ খাওক',
    musicTherapyDetail: 'শান্ত NER লোক সংগীত শুনক',
    sleepPrepDetail: 'পোহৰ নিমিলাওক আৰু জিৰণিৰ বাবে প্ৰস্তুতি লওক',
    todayProgress: 'আজিৰ দৈনিক অগ্ৰগতি',
    currentTime: 'বৰ্তমান সময়',
    overallProgress: 'সামগ্ৰিক অগ্ৰগতি',
    medicinesLabel: 'ঔষধ',
    hydrationLabel: 'জলযোজন',
    allTaken: 'সকলো লোৱা হৈছে!',
    wellHydrated: 'ভালদৰে জলযুক্ত!',
    drinkMoreWater: 'বেছি পানী খাওক',
    memoryMatch: 'ল্যান্ডমাৰ্ক স্মৃতি',
    melodyMemory: 'সুৰৰ স্মৃতি',
    dailyRoutine: 'দৈনিক ৰুটিন',
    marketSorting: 'বজাৰ সজোৱা',
    patternReplication: 'তাঁত আৰ্হি',
    wordCompletion: 'শব্দ স্মৰণ',
    numberPatterns: 'সংখ্যা আৰ্হি',
    culturalConnections: 'সাংস্কৃতিক সংযোগ',
    colourWord: 'ৰং আৰু শব্দ',
    proverbCompletion: 'প্ৰবাদ জ্ঞান',
  },

  mni: { // Manipuri (Meitei Mayek transliterated)
    appName: 'কোগ্নিকেয়ার NER',
    tagline: 'মেমোরি কেয়ার প্লাটফর্ম',
    patient: 'অনাবা',
    caregiver: 'শেন্নবা',
    games: 'ৱাখল্লোনগী থৌরাং',
    reminders: 'নুমীদাং চিংনবা',
    dashboard: 'ডেশবোর্ড',
    patients: 'অনাবা শেম্নৈ',
    alerts: 'লমজিং',
    settings: 'শেৎপা',
    back: 'হন্দোক্লো',
    next: 'মতমদা',
    play: 'ৱাখল্লো',
    score: 'নম্বর',
    level: 'লেভেল',
    correct: 'ফজবা! অদু ফৈ!',
    tryAgain: 'অমুক হান্না হোৎননবীরো।',
    gameComplete: 'মরম থোকপা! নং ওইখি!',
    medicine: 'লায়েং চাবগী পুক্নিং থৌগৎপা',
    water: 'ঈশিং থক্কো',
    exercise: 'হেন্না নৌপা',
    appointment: 'ডাক্তর লৈবা',
    morning: 'অয়ুক',
    afternoon: 'নুংথিল',
    evening: 'নুংশিৎ',
    selectLanguage: 'লোন',
    selectTheme: 'থিম',
    switchPortal: 'পোর্টাল থুনা',
    patientPortal: 'অনাবা পোর্টাল',
    caregiverPortal: 'শেন্নবা পোর্টাল',
    gamesSubtitle: 'অমা থেংনবা য়ারো। থৌরাং অসিনা নংগী মতম অমত্তা ফিৎনবা লৌ।',
    readAloud: 'হায়রো',
    gamesAvailable: 'থৌরাং শেম্নৈ',
    gamesPlayed: 'থৌরাং ৱাখল্লে',
    overallAccuracy: 'অরোইবা নম্বর',
    welcome: 'কোগ্নিকেয়ার NER-দা য়াম্না পোথোকপা',
    heroSubtitle: 'NER রেগিওন থা অনাবা অমিওৎপা লৌমীশিংগীদমক AI-গী মায়োক্না ৱাখল্লোন।',
    enterPatient: 'অনাবা পোর্টালদা পুরো',
    enterCaregiver: 'শেন্নবা পোর্টালদা পুরো',
    morningMedicine: 'অয়ুকগী লায়েং',
    drinkWater: 'ঈশিং থক্কো',
    morningWalk: 'অয়ুকগী হেন্না',
    brainGames: 'মতম থৌরাং খরা',
    lunchMedicine: 'নুংথিলগী লায়েং',
    afternoonRest: 'নুংথিলগী থম্মোন',
    teaSnack: 'চাহ অমদি খানা',
    eveningWalk: 'নুংশিৎকী হেন্না',
    doctorAppointment: 'ডাক্তর লৈবা',
    eveningMedicine: 'নুংশিৎকী লায়েং',
    musicTherapy: 'ৱারোল ইশৈ',
    sleepPrep: 'থমনবগী তৈয়ারী',
    morningMedicineDetail: 'লায়েং য়াম্না থেংনবা ঈশিংনা থক্কো',
    drinkWaterDetail: 'ঈশিং অমা থক্কো - শরীর লৈবা',
    morningWalkDetail: '১৫ মিনিট নুংঙাইবা হেন্না হোৎনরো',
    brainGamesDetail: '২-৩টা থৌরাং খরা ৱাখল্লো',
    lunchMedicineDetail: 'নুংথিলগী খানার মতুংদা লায়েং থক্কো',
    afternoonRestDetail: '৩০ মিনিট থমম্মোন হোৎনরো',
    teaSnackDetail: 'চাহ অমদি লৈবা খানা',
    eveningWalkDetail: 'নুংশিৎতা হেন্না হোৎনরো',
    doctorAppointmentDetail: 'ডাক্তরনা টেলিফোন্দা লৈবা',
    eveningMedicineDetail: 'ইথৌরগীদমক লায়েং থক্কো',
    musicTherapyDetail: 'NER ৱারোল ইশৈ হায়রো',
    sleepPrepDetail: 'থোকচিল অমদি লায়েং থমনবা তৈয়ারী',
    todayProgress: 'নুপীদা অগ্রগতি',
    currentTime: 'মতম অসিদা',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    medicinesLabel: 'লায়েং',
    hydrationLabel: 'ঈশিং',
    allTaken: 'ফংলে!',
    wellHydrated: 'ঈশিং য়াম্নিংবা!',
    drinkMoreWater: 'ঈশিং য়াম্না থক্কো',
    memoryMatch: 'ল্যান্ডমার্ক হন্থবা',
    melodyMemory: 'ৱারোল হন্থবা',
    dailyRoutine: 'নুপীদা হোৎনবা',
    marketSorting: 'বজার সেৎপা',
    patternReplication: 'ফিগার হন্থবা',
    wordCompletion: 'ৱার্ড হন্থবা',
    numberPatterns: 'নম্বর ফিগার',
    culturalConnections: 'থৌৱারোল সংযোগ',
    colourWord: 'রং অমদি ৱার্ড',
    proverbCompletion: 'ৱাখল জ্ঞান',
  },

  hi: { // Hindi
    appName: 'कॉग्निकेयर NER',
    tagline: 'स्मृति देखभाल मंच',
    patient: 'रोगी',
    caregiver: 'देखभालकर्ता',
    games: 'संज्ञानात्मक खेल',
    reminders: 'दैनिक अनुस्मारक',
    dashboard: 'डैशबोर्ड',
    patients: 'रोगी प्रोफाइल',
    alerts: 'सतर्कताएँ और अंतर्दृष्टि',
    settings: 'सेटिंग',
    back: 'वापस',
    next: 'अगला',
    play: 'खेलें',
    score: 'अंक',
    level: 'स्तर',
    correct: 'बहुत बढ़िया! सही उत्तर!',
    tryAgain: 'लगभग हो गया! फिर कोशिश करें।',
    gameComplete: 'शानदार! आपने अभ्यास पूरा किया!',
    medicine: 'दवाई याद',
    water: 'पानी पियें',
    exercise: 'हल्की कसरत',
    appointment: 'डॉक्टर अपॉइंटमेंट',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    selectLanguage: 'भाषा',
    selectTheme: 'थीम',
    switchPortal: 'पोर्टल बदलें',
    patientPortal: 'रोगी पोर्टल',
    caregiverPortal: 'देखभालकर्ता पोर्टल',
    gamesSubtitle: 'एक अभ्यास चुनें। प्रत्येक खेल आपके दिमाग के एक अलग हिस्से को प्रशिक्षित करता है।',
    readAloud: 'जोर से पढ़ें',
    gamesAvailable: 'खेल उपलब्ध',
    gamesPlayed: 'खेले गए खेल',
    overallAccuracy: 'कुल सटीकता',
    welcome: 'कॉग्निकेयर NER में आपका स्वागत है',
    heroSubtitle: 'उत्तर-पूर्वी भारत के बुजुर्ग डिमेंशिया रोगियों के लिए AI-संचालित संज्ञानात्मक खेल और स्मृति सहायता।',
    enterPatient: 'रोगी पोर्टल में प्रवेश करें',
    enterCaregiver: 'देखभालकर्ता पोर्टल में प्रवेश करें',
    morningMedicine: 'सुबह की दवाई',
    drinkWater: 'पानी पियें',
    morningWalk: 'सुबह की सैर',
    brainGames: 'दिमागी खेल का समय',
    lunchMedicine: 'दोपहर की दवाई',
    afternoonRest: 'आराम और झपकी',
    teaSnack: 'चाय और नाश्ता',
    eveningWalk: 'शाम की सैर',
    doctorAppointment: 'डॉक्टर अपॉइंटमेंट',
    eveningMedicine: 'शाम की दवाई',
    musicTherapy: 'संगीत चिकित्सा',
    sleepPrep: 'नींद की तैयारी',
    morningMedicineDetail: 'गर्म पानी के साथ सुबह की गोलियाँ लें',
    drinkWaterDetail: 'एक गिलास गर्म पानी पियें — हाइड्रेटेड रहें',
    morningWalkDetail: 'बगीचे में 15 मिनट की हल्की सैर',
    brainGamesDetail: 'मानसिक उत्तेजना के लिए 2-3 खेल खेलें',
    lunchMedicineDetail: 'दोपहर के खाने के बाद दवाई लें',
    afternoonRestDetail: 'ठीक होने के लिए 30 मिनट का आराम',
    teaSnackDetail: 'असम की चाय और हल्के नाश्ते का आनंद लें',
    eveningWalkDetail: 'ताज़ी हवा के लिए छोटी शाम की सैर',
    doctorAppointmentDetail: 'न्यूरोलॉजिस्ट के साथ साप्ताहिक टेली-परामर्श',
    eveningMedicineDetail: 'रात के खाने के साथ शाम की दवाई लें',
    musicTherapyDetail: 'शांत NER लोक संगीत सुनें',
    sleepPrepDetail: 'रोशनी कम करें और आरामदायक नींद की तैयारी करें',
    todayProgress: 'आज की दैनिक प्रगति',
    currentTime: 'वर्तमान समय',
    overallProgress: 'कुल प्रगति',
    medicinesLabel: 'दवाइयाँ',
    hydrationLabel: 'जलयोजन',
    allTaken: 'सब ले लिया!',
    wellHydrated: 'अच्छी तरह हाइड्रेटेड!',
    drinkMoreWater: 'और पानी पियें',
    memoryMatch: 'लैंडमार्क स्मृति',
    melodyMemory: 'धुन स्मृति',
    dailyRoutine: 'दैनिक दिनचर्या',
    marketSorting: 'बाज़ार छँटाई',
    patternReplication: 'बुनाई पैटर्न',
    wordCompletion: 'शब्द स्मरण',
    numberPatterns: 'संख्या पैटर्न',
    culturalConnections: 'सांस्कृतिक संबंध',
    colourWord: 'रंग और शब्द',
    proverbCompletion: 'कहावत ज्ञान',
  },

  bn: { // Bengali
    appName: 'কগ্নিকেয়ার NER',
    tagline: 'স্মৃতি যত্ন মঞ্চ',
    patient: 'রোগী',
    caregiver: 'পরিচর্যাকারী',
    games: 'জ্ঞানমূলক খেলা',
    reminders: 'দৈনিক অনুস্মারক',
    dashboard: 'ড্যাশবোর্ড',
    patients: 'রোগীর প্রোফাইল',
    alerts: 'সতর্কতা ও অন্তর্দৃষ্টি',
    settings: 'সেটিং',
    back: 'পিছনে',
    next: 'পরবর্তী',
    play: 'খেলুন',
    score: 'স্কোর',
    level: 'স্তর',
    correct: 'চমৎকার! সঠিক উত্তর!',
    tryAgain: 'প্রায় হয়ে গেছে! আবার চেষ্টা করুন।',
    gameComplete: 'অসাধারণ! আপনি অনুশীলন সম্পন্ন করলেন!',
    medicine: 'ওষুধের অনুস্মারক',
    water: 'জল পান করুন',
    exercise: 'হালকা ব্যায়াম',
    appointment: 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
    morning: 'সকাল',
    afternoon: 'দুপুর',
    evening: 'সন্ধ্যা',
    selectLanguage: 'ভাষা',
    selectTheme: 'থিম',
    switchPortal: 'পোর্টাল বদলান',
    patientPortal: 'রোগী পোর্টাল',
    caregiverPortal: 'পরিচর্যাকারী পোর্টাল',
    gamesSubtitle: 'একটি অনুশীলন বেছে নিন। প্রতিটি খেলা আপনার মনের আলাদা অংশকে প্রশিক্ষণ দেয়।',
    readAloud: 'জোরে পড়ুন',
    gamesAvailable: 'খেলা উপলব্ধ',
    gamesPlayed: 'খেলা খেলেছেন',
    overallAccuracy: 'সামগ্রিক নির্ভুলতা',
    welcome: 'কগ্নিকেয়ার NER-এ স্বাগতম',
    heroSubtitle: 'উত্তর-পূর্ব ভারতের বৃদ্ধ ডিমেনশিয়া রোগীদের জন্য AI-চালিত জ্ঞানমূলক খেলা এবং স্মৃতি সহায়তা।',
    enterPatient: 'রোগী পোর্টালে প্রবেশ করুন',
    enterCaregiver: 'পরিচর্যাকারী পোর্টালে প্রবেশ করুন',
    morningMedicine: 'সকালের ওষুধ',
    drinkWater: 'জল পান করুন',
    morningWalk: 'সকালের হাঁটা',
    brainGames: 'মস্তিষ্কের খেলার সময়',
    lunchMedicine: 'দুপুরের ওষুধ',
    afternoonRest: 'বিশ্রাম ও ঘুম',
    teaSnack: 'চা ও নাস্তা',
    eveningWalk: 'সন্ধ্যার হাঁটা',
    doctorAppointment: 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
    eveningMedicine: 'সন্ধ্যার ওষুধ',
    musicTherapy: 'সংগীত থেরাপি',
    sleepPrep: 'ঘুমের প্রস্তুতি',
    morningMedicineDetail: 'গরম জল দিয়ে সকালের বড়ি নিন',
    drinkWaterDetail: 'এক গ্লাস গরম জল পান করুন - হাইড্রেটেড থাকুন',
    morningWalkDetail: 'বাগানে ১৫ মিনিট সহজে হাঁটুন',
    brainGamesDetail: 'মানসিক উদ্দীপনার জন্য ২-৩টি খেলা খেলুন',
    lunchMedicineDetail: 'দুপুরের খাবারের পরে ওষুধ নিন',
    afternoonRestDetail: 'সুস্থতার জন্য সংক্ষিপ্ত ৩০ মিনিটের বিশ্রাম',
    teaSnackDetail: 'আসাম চা এবং হালকা স্বাস্থ্যকর নাস্তা উপভোগ করুন',
    eveningWalkDetail: 'তাজা বাতাসের জন্য সংক্ষিপ্ত সন্ধ্যার হাঁটা',
    doctorAppointmentDetail: 'নিউরোলজিস্টের সাথে সাপ্তাহিক টেলি-পরামর্শ',
    eveningMedicineDetail: 'রাতের খাবারের সাথে সন্ধ্যার ওষুধ নিন',
    musicTherapyDetail: 'শান্ত NER লোক সংগীত শুনুন',
    sleepPrepDetail: 'আলো কমান এবং প্রশান্তির ঘুমের জন্য প্রস্তুতি নিন',
    todayProgress: 'আজকের দৈনিক অগ্রগতি',
    currentTime: 'বর্তমান সময়',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    medicinesLabel: 'ওষুধ',
    hydrationLabel: 'জলযোজন',
    allTaken: 'সব নেওয়া হয়েছে!',
    wellHydrated: 'ভালোভাবে হাইড্রেটেড!',
    drinkMoreWater: 'আরও জল পান করুন',
    memoryMatch: 'ল্যান্ডমার্ক স্মৃতি',
    melodyMemory: 'সুর স্মৃতি',
    dailyRoutine: 'দৈনিক রুটিন',
    marketSorting: 'বাজার সাজানো',
    patternReplication: 'বুনন নকশা',
    wordCompletion: 'শব্দ স্মরণ',
    numberPatterns: 'সংখ্যা নকশা',
    culturalConnections: 'সাংস্কৃতিক সংযোগ',
    colourWord: 'রঙ ও শব্দ',
    proverbCompletion: 'প্রবাদ জ্ঞান',
  },

  kha: { // Khasi
    appName: 'CogniCare NER',
    tagline: 'Jingïaphaw jingmut platform',
    patient: 'U bynriew uba ïap',
    caregiver: 'U nongpynïaid',
    games: 'Ki khynraw jingmut',
    reminders: 'Ki jingpynmaw sngi',
    dashboard: 'Dashboard',
    patients: 'Ki profile ki bynriew',
    alerts: 'Ki jingpynmaw balang',
    settings: 'Ki setting',
    back: 'Shakhmat',
    next: 'Kynmaw',
    play: 'Ia khynraw',
    score: 'Score',
    level: 'Level',
    correct: 'Babha! Dei bha!',
    tryAgain: 'Sngewbha beit ha ka jingthoh!',
    gameComplete: 'Babha khawp! Ngi pynmih la!',
    medicine: 'Ka jingpynïaid dawai',
    water: 'Dih um',
    exercise: 'Jingwang rit',
    appointment: 'Appointment doctor',
    morning: 'Sngi pyllong',
    afternoon: 'Sngi rangbah',
    evening: 'Sngi shibun',
    selectLanguage: 'Ka ktien',
    selectTheme: 'Theme',
    switchPortal: 'Leit sha portal pat',
    patientPortal: 'Portal ki bynriew',
    caregiverPortal: 'Portal ki nongpynïaid',
    gamesSubtitle: 'Tip ia ka khynraw bait. Ki khynraw kynmaw pynïaid ki poïaid ki mih kit.',
    readAloud: 'Pynïaid mariang',
    gamesAvailable: 'Ki khynraw don',
    gamesPlayed: 'Ki khynraw la ia khynraw',
    overallAccuracy: 'Jingthoh bha pyrthei',
    welcome: 'Wan sha CogniCare NER',
    heroSubtitle: 'AI jingïaid ka jingkhynraw jingmut bad jingphah jingmut sha ki khynnah ïaid ha NER.',
    enterPatient: 'Leit sha portal ki bynriew',
    enterCaregiver: 'Leit sha portal ki nongpynïaid',
    morningMedicine: 'Dawai sngi pyllong',
    drinkWater: 'Dih um',
    morningWalk: 'Jingwang sngi pyllong',
    brainGames: 'Myntoi khynraw jingmut',
    lunchMedicine: 'Dawai ba ngi bam khana',
    afternoonRest: 'Jingïoh bad jingkhuid',
    teaSnack: 'Sha bad khana rit',
    eveningWalk: 'Jingwang sngi shibun',
    doctorAppointment: 'Appointment doctor',
    eveningMedicine: 'Dawai sngi shibun',
    musicTherapy: 'Jingtip musiQ NER',
    sleepPrep: 'Jingbeit sha jingkhuid',
    morningMedicineDetail: 'Ioh dawai kylliang bad um myntoi',
    drinkWaterDetail: 'Dih um amet - ioh shaïing',
    morningWalkDetail: '15 myntoi jingwang rit ha lum',
    brainGamesDetail: '2-3 ki khynraw jingmut',
    lunchMedicineDetail: 'Ioh dawai ïoh la khana sngi rangbah',
    afternoonRestDetail: '30 myntoi jingïoh ka jingbeit',
    teaSnackDetail: 'Tip sha ba sngewïoh',
    eveningWalkDetail: 'Jingwang rit ha sngi shibun',
    doctorAppointmentDetail: 'Tele-jaied ba doctor tymmen',
    eveningMedicineDetail: 'Ioh dawai ïoh la bam khana khynnah',
    musicTherapyDetail: 'Tip musiQ NER ba pynsngewbha',
    sleepPrepDetail: 'Pyndap dieng bad ioh shaïing sha jingkhuid',
    todayProgress: 'Ka jingiapbha sngi mynta',
    currentTime: 'Myntoi ngi biang',
    overallProgress: 'Jingïapbha shibun',
    medicinesLabel: 'Ki dawai',
    hydrationLabel: 'Ka um',
    allTaken: 'Ioh la katno!',
    wellHydrated: 'Ka um bha!',
    drinkMoreWater: 'Dih um yot',
    memoryMatch: 'Jingmut ki landmark',
    melodyMemory: 'Jingmut melody',
    dailyRoutine: 'Jingïaid sngi',
    marketSorting: 'Jingptiah bazaar',
    patternReplication: 'Ki pattern tyngkong',
    wordCompletion: 'Jingmut ki word',
    numberPatterns: 'Ki pattern nambor',
    culturalConnections: 'Ki jingkyndong iing seng',
    colourWord: 'Rang bad word',
    proverbCompletion: 'Ka jingïing iing',
  },

  mzo: { // Mizo
    appName: 'CogniCare NER',
    tagline: 'Hre thar platform',
    patient: 'Damlo mi',
    caregiver: 'Enkawl tu',
    games: 'Infiamna zirchian',
    reminders: 'Nihna zirtirtu',
    dashboard: 'Dashboard',
    patients: 'Damlo mi profile',
    alerts: 'Thupek',
    settings: 'Setting',
    back: 'Kir leh',
    next: 'Zawn leh',
    play: 'Tui leh',
    score: 'Score',
    level: 'Level',
    correct: 'Tha khawp mai! A dik!',
    tryAgain: 'Tum leh teh ang!',
    gameComplete: 'Ropui tak! I tih zo ta!',
    medicine: 'Damdawi ei tur hriattir',
    water: 'Tui in rawh',
    exercise: 'Zawn tui',
    appointment: 'Doctor appointment',
    morning: 'Zingkar',
    afternoon: 'Chawlhkar',
    evening: 'Thlakthleng',
    selectLanguage: 'Tawng',
    selectTheme: 'Theme',
    switchPortal: 'Portal thlak',
    patientPortal: 'Damlo mi portal',
    caregiverPortal: 'Enkawl tu portal',
    gamesSubtitle: 'Infiamna pakhat thlang rawh. Infiamna tin i lungril a danglam thlang a zir.',
    readAloud: 'Hla sawt pe',
    gamesAvailable: 'Infiamna awm',
    gamesPlayed: 'Infiamna tuah',
    overallAccuracy: 'Score lawmawm',
    welcome: 'CogniCare NER-a i kal chhuah',
    heroSubtitle: 'NER thlengah damlo pa mi upa leh hmasawnna tan AI-in infiamna zirchian.',
    enterPatient: 'Damlo mi portal-a lut',
    enterCaregiver: 'Enkawl tu portal-a lut',
    morningMedicine: 'Zingkar damdawi',
    drinkWater: 'Tui in rawh',
    morningWalk: 'Zingkar zawn',
    brainGames: 'Lungril infiamna',
    lunchMedicine: 'Chawlhkar damdawi',
    afternoonRest: 'Khawlzin leh ninna',
    teaSnack: 'Chhah leh ei bawm',
    eveningWalk: 'Thlakthleng zawn',
    doctorAppointment: 'Doctor appointment',
    eveningMedicine: 'Thlakthleng damdawi',
    musicTherapy: 'Hla NER siamtu',
    sleepPrep: 'Ninna tana beisei',
    morningMedicineDetail: 'Tui zuang nên zingkar damdawi ei rawh',
    drinkWaterDetail: 'Tui hmet khat in rawh — dam rawh',
    morningWalkDetail: '15 minit zingkar a tlang zawn',
    brainGamesDetail: '2–3 lungril infiamna tui ang',
    lunchMedicineDetail: 'Chawlh hnuah damdawi ei rawh',
    afternoonRestDetail: '30 minit khawlzin tih rawh',
    teaSnackDetail: 'Assam chhah leh ei bawm lawm rawh',
    eveningWalkDetail: 'Thlakthleng-ah zawn tui ang',
    doctorAppointmentDetail: 'Damlo doctor tele-appointment khat',
    eveningMedicineDetail: 'Tzan ei tawh zawnin thlakthleng damdawi ei rawh',
    musicTherapyDetail: 'NER hla siamtu zang zawng zawng hre rawh',
    sleepPrepDetail: 'Vawlel leh ninna tana beisei rawh',
    todayProgress: 'Tun thleng progress',
    currentTime: 'Hun thleng',
    overallProgress: 'Lawmawm progress',
    medicinesLabel: 'Damdawi',
    hydrationLabel: 'Tui',
    allTaken: 'Zawh ta!',
    wellHydrated: 'Tui yo ta!',
    drinkMoreWater: 'Tui yo zawng in rawh',
    memoryMatch: 'Landmark hre thar',
    melodyMemory: 'Melody hre thar',
    dailyRoutine: 'Nihin hna',
    marketSorting: 'Bazaar sawisel',
    patternReplication: 'Zo pattern hre thar',
    wordCompletion: 'Thu hre thar',
    numberPatterns: 'Nambur pattern',
    culturalConnections: 'Mimal inthlahna',
    colourWord: 'Rang leh thu',
    proverbCompletion: 'Lehkha thiam',
  },
};

// ============================================================
// THEMES
// ============================================================
export const THEMES = {
  green: {
    name: 'Forest Green',
    emoji: '🌿',
    '--bg-primary': '#F2F7F2',
    '--bg-secondary': '#FFFFFF',
    '--bg-sidebar': '#0B3D3D',
    '--accent-teal': '#0A7E6A',
    '--accent-green': '#1D9B5F',
    '--gradient-primary': 'linear-gradient(135deg, #0A7E6A 0%, #1D9B5F 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #E8F8F0 0%, #F5EFE6 40%, #E4F5E9 100%)',
    '--accent-teal-light': 'rgba(10,126,106,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(10,126,106,0.12) 0%, transparent 70%)',
  },
  blue: {
    name: 'Ocean Blue',
    emoji: '🌊',
    '--bg-primary': '#F0F4FF',
    '--bg-secondary': '#FFFFFF',
    '--bg-sidebar': '#1A2A4A',
    '--accent-teal': '#1B66C9',
    '--accent-green': '#0D8FA4',
    '--gradient-primary': 'linear-gradient(135deg, #1B66C9 0%, #0D8FA4 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #E8F0FF 0%, #F0F8FF 40%, #E0F5FA 100%)',
    '--accent-teal-light': 'rgba(27,102,201,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(27,102,201,0.12) 0%, transparent 70%)',
  },
  purple: {
    name: 'Twilight Purple',
    emoji: '🌸',
    '--bg-primary': '#F6F2FF',
    '--bg-secondary': '#FFFFFF',
    '--bg-sidebar': '#2D1B4E',
    '--accent-teal': '#7C3AED',
    '--accent-green': '#9D44DE',
    '--gradient-primary': 'linear-gradient(135deg, #7C3AED 0%, #9D44DE 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #F3EEFF 0%, #FFF0F9 40%, #EDE8FF 100%)',
    '--accent-teal-light': 'rgba(124,58,237,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(124,58,237,0.12) 0%, transparent 70%)',
  },
  amber: {
    name: 'Warm Saffron',
    emoji: '🌻',
    '--bg-primary': '#FFFBF0',
    '--bg-secondary': '#FFFFFF',
    '--bg-sidebar': '#3D2400',
    '--accent-teal': '#C47A00',
    '--accent-green': '#A65D00',
    '--gradient-primary': 'linear-gradient(135deg, #E08B00 0%, #C47A00 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #FFF8E0 0%, #FFF0D6 40%, #FFEBC0 100%)',
    '--accent-teal-light': 'rgba(196,122,0,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(196,122,0,0.12) 0%, transparent 70%)',
  },
};

const AppContext = createContext();

export function AppProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('cogni_lang') || 'en');
  const [theme, setTheme] = useState(() => localStorage.getItem('cogni_theme') || 'green');
  const [gameScores, setGameScores] = useState(() => {
    try { return JSON.parse(localStorage.getItem('cogni_scores') || '[]'); } catch { return []; }
  });

  // Persist language
  useEffect(() => { localStorage.setItem('cogni_lang', language); }, [language]);
  // Persist theme
  useEffect(() => { localStorage.setItem('cogni_theme', theme); }, [theme]);
  // Persist scores
  useEffect(() => { localStorage.setItem('cogni_scores', JSON.stringify(gameScores)); }, [gameScores]);

  // Apply theme CSS variables to :root
  useEffect(() => {
    const t = THEMES[theme] || THEMES.green;
    const root = document.documentElement;
    Object.entries(t).forEach(([key, val]) => {
      if (key.startsWith('--')) root.style.setProperty(key, val);
    });
  }, [theme]);

  // Translation function — falls back to English key
  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  const addScore = (gameName, score, maxScore, responseTimeMs) => {
    const entry = {
      id: Date.now(),
      game: gameName,
      score,
      maxScore,
      accuracy: Math.round((score / maxScore) * 100),
      responseTimeMs,
      timestamp: new Date().toISOString(),
      language,
    };
    setGameScores(prev => [entry, ...prev].slice(0, 200));
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, theme, setTheme, t, gameScores, addScore }}>
      {children}
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);

export const SUPPORTED_LANGUAGES = [
  { code: 'en',  label: 'English',   native: 'English',     ttsLang: 'en-IN' },
  { code: 'as',  label: 'Assamese',  native: 'অসমীয়া',      ttsLang: 'as-IN' },
  { code: 'mni', label: 'Manipuri',  native: 'মৈতৈলোন্',     ttsLang: 'hi-IN' },
  { code: 'bn',  label: 'Bengali',   native: 'বাংলা',        ttsLang: 'bn-IN' },
  { code: 'kha', label: 'Khasi',     native: 'Khasi',        ttsLang: 'en-IN' },
  { code: 'mzo', label: 'Mizo',      native: 'Mizo ṭawng',   ttsLang: 'en-IN' },
  { code: 'hi',  label: 'Hindi',     native: 'हिन्दी',        ttsLang: 'hi-IN' },
];
