import { createContext, useContext, useState, useEffect } from 'react';

// ============================================================
// COMPLETE TRANSLATIONS — all UI text in all 7 NER languages
// ============================================================
const TRANSLATIONS = {
  en: {
    'Across 8 cognitive domains': 'Across 8 cognitive domains',
    'Great engagement!': 'Great engagement!',
    'Try more games!': 'Try more games!',
    'AI Difficulty Level': 'AI Difficulty Level',
    'Level': 'Level',
    'Auto-adapted to your skill': 'Auto-adapted to your skill',
    'Music Therapy': 'Music Therapy',
    'Family Faces': 'Family Faces',
    'Odd One Out': 'Odd One Out',
    'Therapy': 'Therapy',
    'Personal': 'Personal',
    'Categorization': 'Categorization',
    'Memory': 'Memory',
    'Auditory Memory': 'Auditory Memory',
    'Executive Fn': 'Executive Fn',
    'Numerical': 'Numerical',
    'Semantic Memory': 'Semantic Memory',
    'Attention': 'Attention',
    'Language': 'Language',
    'Lexical': 'Lexical',
    'Visuospatial': 'Visuospatial',
    'Easy': 'Easy',
    'Medium': 'Medium',
    'Hard': 'Hard',
    'Calming algorithmic NER folk melodies for sundowning relief': 'Calming algorithmic NER folk melodies for sundowning relief',
    'Recognize your family members and loved ones from uploaded photos': 'Recognize your family members and loved ones from uploaded photos',
    'Find the item that does not belong in the category': 'Find the item that does not belong in the category',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'Arrange morning tea brewing, self-care, and garden routines in correct order',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'Complete NER folk proverbs — "The bamboo that bends is stronger than..."',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'Memorize highlighted handloom weave cells, then replicate from memory',

    appName: 'CogniCare NER',
    tagline: 'Memory Care Platform',
    patient: 'Patient',
    caregiver: 'Caregiver',
    games: 'Cognitive Games',
    reminders: 'Daily Reminders',
    dashboard: 'Dashboard',
    patients: 'Patient Profiles',
    alerts: 'Alerts & Insights',
    settings: 'Settings',
    back: 'Back',
    next: 'Next',
    play: 'Play',
    score: 'Score',
    level: 'Level',
    correct: 'Well done! That is correct!',
    tryAgain: 'Almost! Try once more.',
    gameComplete: 'Wonderful! You completed the exercise!',
    medicine: 'Medicine Reminder',
    water: 'Drink Water',
    exercise: 'Light Exercise',
    appointment: 'Doctor Appointment',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    selectLanguage: 'Language',
    selectTheme: 'Theme',
    switchPortal: 'Switch Portal',
    patientPortal: 'Patient Portal',
    caregiverPortal: 'Caregiver Portal',
    gamesSubtitle: 'Choose an exercise to begin. Each game trains a different part of your mind.',
    readAloud: 'Read Aloud',
    gamesAvailable: 'Games Available',
    gamesPlayed: 'Games Played',
    overallAccuracy: 'Overall Accuracy',
    welcome: 'Welcome to CogniCare NER',
    heroSubtitle: 'AI-powered cognitive gaming and memory assistance for elderly dementia patients across India\'s North Eastern Region.',
    enterPatient: 'Enter Patient Portal',
    enterCaregiver: 'Enter Caregiver Portal',
    // Reminder labels
    morningMedicine: 'Morning Medicine',
    drinkWater: 'Drink Water',
    morningWalk: 'Morning Walk',
    brainGames: 'Brain Games Time',
    lunchMedicine: 'Lunch Medicine',
    afternoonRest: 'Rest & Nap',
    teaSnack: 'Tea & Snack',
    eveningWalk: 'Evening Walk',
    doctorAppointment: 'Doctor Appointment',
    eveningMedicine: 'Evening Medicine',
    musicTherapy: 'Music Therapy',
    sleepPrep: 'Sleep Preparation',
    smritiPhone: 'Smriti Phone',
    smritiPhoneDesc: 'Talk to your AI companion in your native language.',
    howAreYouFeeling: 'How are you feeling today?',
    moodCheckInDesc: 'Take a moment to let us know how you are feeling.',
    // Reminder details
    morningMedicineDetail: 'Take prescribed morning tablets with warm water',
    drinkWaterDetail: 'Have a glass of warm water — stay hydrated',
    morningWalkDetail: '15-minute gentle walk in the garden',
    brainGamesDetail: 'Play 2–3 cognitive exercises for mental stimulation',
    lunchMedicineDetail: 'Take prescribed afternoon tablets after lunch',
    afternoonRestDetail: 'Short 30-minute rest for recovery',
    teaSnackDetail: 'Enjoy Assam tea with light wholesome snacks',
    eveningWalkDetail: 'Short evening walk for fresh air',
    doctorAppointmentDetail: 'Weekly tele-consultation with neurologist',
    eveningMedicineDetail: 'Take prescribed evening tablets with dinner',
    musicTherapyDetail: 'Listen to calming NER folk music',
    sleepPrepDetail: 'Dim lights and prepare for restful sleep',
    // Progress / KPIs
    todayProgress: "Today's Daily Progress",
    currentTime: 'Current Time',
    overallProgress: 'Overall Progress',
    medicinesLabel: 'Medicines',
    hydrationLabel: 'Hydration',
    allTaken: 'All taken!',
    wellHydrated: 'Well hydrated!',
    drinkMoreWater: 'Drink more water',
    // Game titles
    memoryMatch: 'Landmark Memory',
    melodyMemory: 'Melody Memory',
    dailyRoutine: 'Daily Routine',
    marketSorting: 'Bazaar Sorting',
    patternReplication: 'Weaving Patterns',
    wordCompletion: 'Word Recall',
    numberPatterns: 'Number Patterns',
    culturalConnections: 'Cultural Connections',
    colourWord: 'Colour & Word',
    proverbCompletion: 'Proverb Wisdom',
    oddOneOut: 'Odd One Out',
    familyFaces: 'Family Faces',
    addReminder: 'Add Custom Reminder',
    addReminderBtn: '+ Add Reminder',
    saveReminder: 'Save Reminder',
    cancel: 'Cancel',
    timeLabel: 'Time',
    titleLabel: 'Title',
    detailLabel: 'Details',
    // SmritiPhone & CalmMode
    phoneTitle: 'Smriti Saathi Phone',
    radioTitle: 'Smriti Radio & 40Hz Therapy',
    radioDesc: 'Nostalgic algorithmic music therapy for calming and sundowning relief.',
    gammaTherapy: '40Hz Gamma Therapy',
    gammaDesc: 'Reduces amyloid plaques',
    powerOff: 'POWER OFF',
    callEnded: 'Call Ended',
    calling: 'Calling...',
    readyToCall: 'Ready to call...',
    listening: 'Listening...',
    biomarkerAnalysis: 'AI Speech Biomarker Analysis',
    wordsSpoken: 'Words Spoken',
    fillerWords: 'Filler Words',
    fluencyScore: 'Fluency Score',
  },

  as: {
    'Caregiver Dashboard': 'পৰিচৰ্যাকাৰী ডেছবোৰ্ড',
    'Monitor cognitive performance, track engagement trends, and receive AI-powered clinical insights.': 'জ্ঞানমূলক প্ৰদৰ্শন নিৰীক্ষণ কৰক, ট্ৰেণ্ডসমূহ অনুসৰণ কৰক আৰু AI-চালিত ক্লিনিকেল অন্তৰ্দৃষ্টি লাভ কৰক।',
    'Cognitive Wellness Index': 'জ্ঞানমূলক সুস্থতা সূচক',
    'Out of 100': '১০০ৰ ভিতৰত',
    'AI Multi-Signal Attribution': 'AI মাল্টি-চিগনেল এট্ৰিবিউচন',
    'Game Performance': 'খেলৰ প্ৰদৰ্শন',
    'Emotional Stability': 'আৱেগিক স্থিৰতা',
    'Speech Fluency Biomarker': 'কথন সাৱলীলতা বায়োমাৰ্কাৰ',
    'Sessions This Week': 'এই সপ্তাহৰ অধিবেশনসমূহ',
    'Average Accuracy': 'গড় নিখুঁততা',
    'Avg Response Time': 'গড় সঁহাৰিৰ সময়',
    'Active Streak': 'সক্ৰিয় ধাৰাবাহিকতা',
    'Reminders Completed': 'সোঁৱৰণী সম্পূৰ্ণ',
    'Caregiver Wellbeing': 'পৰিচৰ্যাকাৰীৰ সুস্থতা',
    'Sundowning Pattern Detected': 'ছানডাউনিং আৰ্হি ধৰা পৰিছে',
    'CRITICAL': 'জটিল',
    'AI Recommendation:': 'AI পৰামৰ্শ:',
    '7-Day Cognitive Performance': '৭-দিনীয়া জ্ঞানমূলক প্ৰদৰ্শন',
    'Accuracy & response time trends': 'নিখুঁততা আৰু সঁহাৰিৰ সময়ৰ ট্ৰেণ্ড',
    'Cognitive Digital Twin': 'জ্ঞানমূলক ডিজিটেল টুইন',
    'Radar mapping of 6 brain domains (CST)': '৬টা মগজু ডমেইনৰ ৰাডাৰ মেপিং',
    'Patient Mood Trend': 'ৰোগীৰ মেজাজৰ ট্ৰেণ্ড',
    'Self-reported pre-session emotional state': 'অধিবেশনৰ পূৰ্বৰ আৱেগিক অৱস্থা',
    'Conversational Cognitive Signal': 'কথোপকথনমূলক জ্ঞানমূলক সংকেত',
    'Speech fluency biomarker from Smriti Phone': 'স্মৃতি ফোনৰ পৰা কথন সাৱলীলতা বায়োমাৰ্কাৰ',
    'Recent Game Sessions': 'শেহতীয়া খেলৰ অধিবেশনসমূহ',
    'Detailed session history with accuracy tracking': 'নিখুঁততা ট্ৰেকিংৰ সৈতে বিতং অধিবেশনৰ ইতিহাস',
    'Live Analysis': 'লাইভ বিশ্লেষণ',
    'Accuracy': 'নিখুঁততা',
    'Performance': 'প্ৰদৰ্শন',
    'Time': 'সময়',
    'Game Exercise': 'খেলৰ অনুশীলন',
 // Assamese
    appName: 'কগ্নিকেয়াৰ NER',
    tagline: 'স্মৃতি যত্ন মঞ্চ',
    patient: 'ৰোগী',
    caregiver: 'পৰিচৰ্যাকাৰী',
    games: 'জ্ঞানমূলক খেল',
    reminders: 'দৈনিক সোঁৱৰণী',
    dashboard: 'ডেছবোৰ্ড',
    patients: 'ৰোগীৰ তথ্য',
    alerts: 'সতৰ্কবাৰ্তা',
    settings: 'ছেটিং',
    back: 'পিছলৈ',
    next: 'পৰৱৰ্তী',
    play: 'খেলক',
    score: 'নম্বৰ',
    level: 'স্তৰ',
    correct: 'বঢ়িয়া! শুদ্ধ উত্তৰ!',
    tryAgain: 'প্ৰায় হৈছিল! আকৌ চেষ্টা কৰক।',
    gameComplete: 'অসাধাৰণ! আপুনি অনুশীলন সম্পূৰ্ণ কৰিলে!',
    medicine: 'ঔষধৰ সোঁৱৰণী',
    water: 'পানী খাওক',
    exercise: 'লঘু ব্যায়াম',
    appointment: 'চিকিৎসকৰ পৰামৰ্শ',
    morning: 'ৰাতিপুৱা',
    afternoon: 'দুপৰীয়া',
    evening: 'সন্ধিয়া',
    selectLanguage: 'ভাষা',
    selectTheme: 'থিম',
    switchPortal: 'পৰ্টেল সলনি',
    patientPortal: 'ৰোগী পৰ্টেল',
    caregiverPortal: 'পৰিচৰ্যাকাৰী পৰ্টেল',
    gamesSubtitle: 'এটা অনুশীলন বাছি লওক। প্ৰতিটো খেলে আপোনাৰ মনৰ বেলেগ অংশ প্ৰশিক্ষণ দিয়ে।',
    readAloud: 'জোৰেৰে পঢ়ক',
    gamesAvailable: 'খেল উপলব্ধ',
    gamesPlayed: 'খেল খেলিলে',
    overallAccuracy: 'সামগ্ৰিক নিখুঁততা',
    welcome: 'কগ্নিকেয়াৰ NER-লৈ স্বাগতম',
    heroSubtitle: 'উত্তৰ-পূব ভাৰতৰ বৃদ্ধ ডিমেনছিয়া ৰোগীসকলৰ বাবে AI-চালিত জ্ঞানমূলক খেল আৰু স্মৃতি সহায়তা।',
    enterPatient: 'ৰোগী পৰ্টেলত প্ৰৱেশ',
    enterCaregiver: 'পৰিচৰ্যাকাৰী পৰ্টেলত প্ৰৱেশ',
    morningMedicine: 'ৰাতিপুৱাৰ ঔষধ',
    drinkWater: 'পানী খাওক',
    morningWalk: 'ৰাতিপুৱাৰ খোজকঢ়া',
    brainGames: 'মগজুৰ খেলৰ সময়',
    lunchMedicine: 'দুপৰীয়াৰ ঔষধ',
    afternoonRest: 'জিৰণি আৰু টোপনি',
    teaSnack: 'চাহ আৰু জলপান',
    eveningWalk: 'সন্ধিয়াৰ খোজকঢ়া',
    doctorAppointment: 'চিকিৎসকৰ পৰামৰ্শ',
    eveningMedicine: 'সন্ধিয়াৰ ঔষধ',
    musicTherapy: 'সংগীত চিকিৎসা',
    sleepPrep: 'শোৱাৰ প্ৰস্তুতি',
    morningMedicineDetail: 'ৰাতিপুৱাৰ বড়িসমূহ গৰম পানীৰে খাওক',
    drinkWaterDetail: 'এগিলাচ গৰম পানী খাওক - জলযুক্ত থাকক',
    morningWalkDetail: 'বাগিচাত ১৫ মিনিট সহজে খোজকঢ়া',
    brainGamesDetail: 'মানসিক উদ্দীপনাৰ বাবে ২-৩টা খেল খেলক',
    lunchMedicineDetail: 'দুপৰীয়াৰ আহাৰৰ পিছত ঔষধ খাওক',
    afternoonRestDetail: 'পুনৰুদ্ধাৰৰ বাবে চুটি ৩০ মিনিটৰ জিৰণি',
    teaSnackDetail: 'অসমীয়া চাহ আৰু লঘু খাদ্য উপভোগ কৰক',
    eveningWalkDetail: 'তাজা বায়ুৰ বাবে চুটি সন্ধিয়াৰ খোজকঢ়া',
    doctorAppointmentDetail: 'স্নায়ু বিশেষজ্ঞৰ সৈতে সাপ্তাহিক টেলি-পৰামৰ্শ',
    eveningMedicineDetail: 'ৰাতিৰ আহাৰৰ সৈতে সন্ধিয়াৰ ঔষধ খাওক',
    musicTherapyDetail: 'শান্ত NER লোক সংগীত শুনক',
    sleepPrepDetail: 'পোহৰ নিমিলাওক আৰু জিৰণিৰ বাবে প্ৰস্তুতি লওক',
    todayProgress: 'আজিৰ দৈনিক অগ্ৰগতি',
    currentTime: 'বৰ্তমান সময়',
    overallProgress: 'সামগ্ৰিক অগ্ৰগতি',
    medicinesLabel: 'ঔষধ',
    hydrationLabel: 'জলযোজন',
    allTaken: 'সকলো লোৱা হৈছে!',
    wellHydrated: 'ভালদৰে জলযুক্ত!',
    drinkMoreWater: 'বেছি পানী খাওক',
    memoryMatch: 'ল্যান্ডমাৰ্ক স্মৃতি',
    melodyMemory: 'সুৰৰ স্মৃতি',
    dailyRoutine: 'দৈনিক ৰুটিন',
    marketSorting: 'বজাৰ সজোৱা',
    patternReplication: 'তাঁত আৰ্হি',
    wordCompletion: 'শব্দ স্মৰণ',
    numberPatterns: 'সংখ্যা আৰ্হি',
    culturalConnections: 'সাংস্কৃতিক সংযোগ',
    colourWord: 'ৰং আৰু শব্দ',
    proverbCompletion: 'প্ৰবাদ জ্ঞান',
    oddOneOut: 'অস্বাভাৱিক বাছনি কৰক',
    familyFaces: 'পৰিয়ালৰ মুখসমূহ',
    addReminder: 'কাষ্টম সোঁৱৰণী যোগ কৰক',
    addReminderBtn: '+ সোঁৱৰণী যোগ কৰক',
    saveReminder: 'সোঁৱৰণী সংৰক্ষণ কৰক',
    cancel: 'বাতিল কৰক',
    timeLabel: 'সময়',
    titleLabel: 'শিৰোনাম',
    detailLabel: 'বিৱৰণ',
    phoneTitle: 'স্মৃতি সাথি ফোন',
    radioTitle: 'স্মৃতি ৰেডিঅ’ আৰু 40Hz থেৰাপী',
    radioDesc: 'শান্ত আৰু নিদ্ৰাহীনতা উপশমৰ বাবে পুৰণি সুৰীয়া সংগীত চিকিৎসা।',
    gammaTherapy: '40Hz গামা থেৰাপী',
    gammaDesc: 'এমাইলয়ড প্লেক হ্ৰাস কৰে',
    powerOff: 'বন্ধ কৰক',
    callEnded: 'কল সমাপ্ত',
    calling: 'কল কৰা হৈছে...',
    readyToCall: 'কল কৰিবলৈ সাজু...',
    listening: 'শুনি থকা হৈছে...',
    biomarkerAnalysis: 'AI স্পীচ্ছ বায়োমাৰ্কাৰ বিশ্লেষণ',
    wordsSpoken: 'কোৱা শব্দ',
    fillerWords: 'অলাগতিয়াল শব্দ',
    fluencyScore: 'সাৱলীলতাৰ স্কোৰ',
    
    // Missing Dashboard Stats
    'Across 8 cognitive domains': '৮টা জ্ঞানমূলক ডমেইনৰ মাজেৰে',
    'Great engagement!': 'খেলত ভাল ব্যস্ততা!',
    'Try more games!': 'অধিক খেল চেষ্টা কৰক!',
    'AI Difficulty Level': 'AI অসুবিধাৰ স্তৰ',
    'Level': 'স্তৰ',
    'Auto-adapted to your skill': 'আপোনাৰ দক্ষতাৰ লগত স্বয়ংক্ৰিয়ভাৱে খাপ খোৱা',

    // Game Titles
    'Music Therapy': 'মিউজিক থেৰাপি',
    'Family Faces': 'পৰিয়ালৰ মুখ',
    'Odd One Out': 'অড ৱান আউট',

    // Domains
    'Therapy': 'থেৰাপি',
    'Personal': 'ব্যক্তিগত',
    'Categorization': 'শ্ৰেণীবিভাজন',
    'Memory': 'স্মৃতি',
    'Auditory Memory': 'শ্ৰৱণ স্মৃতি',
    'Executive Fn': 'কাৰ্যবাহী কাৰ্য',
    'Numerical': 'সাংখ্যিক',
    'Semantic Memory': 'অৰ্থগত স্মৃতি',
    'Attention': 'মনোযোগ',
    'Language': 'ভাষা',
    'Lexical': 'শাব্দিক',
    'Visuospatial': 'দৃষ্টিনন্দন',

    // Difficulty
    'Easy': 'সহজ',
    'Medium': 'মাধ্যম',
    'Hard': 'কঠিন',

    // Game Descriptions
    'Calming algorithmic NER folk melodies for sundowning relief': 'সূৰ্যাস্তৰ সময়ত সকাহৰ বাবে শান্ত এলগৰিথমিক এন ই আৰ লোক সুৰ',
    'Recognize your family members and loved ones from uploaded photos': 'আপলোড কৰা ফটোৰ পৰা আপোনাৰ পৰিয়ালৰ সদস্য আৰু আপোনজনক চিনি পাওক',
    'Find the item that does not belong in the category': 'যিটো বস্তু শ্ৰেণীৰ অন্তৰ্গত নহয় সেইটো বিচাৰি উলিয়াওক',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'এন ই আৰ ল্যাণ্ডমাৰ্ক কাৰ্ড মিলাওক — কাজিৰঙা, টাৱাং আৰু অধিকৰ সৈতে দৃশ্য-স্থানিক স্মৃতি প্ৰশিক্ষণ দিয়ে',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'অফলাইনত সংশ্লেষিত বিহু ঢোল, পেপা, পুং আৰু বাঁহৰ বাঁহীৰ ক্ৰম মনত পেলাওক',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'ৰাতিপুৱাৰ চাহ বনোৱা, নিজৰ যত্ন লোৱা, আৰু বাগিচাৰ কাম সঠিক ক্ৰমত সজাওক',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'ভোট জলকীয়া, বাঁহৰ গাজ, মেখেলা চাদৰ খাদ্য বনাম হস্তশিল্পৰ পাচিত সজাওক',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'ক্ৰমবোৰত হেৰুওৱা সংখ্যাবোৰ বিচাৰক — চাহৰ পাচি, তামোলৰ থোক, ৫ টকীয়া নোট গণনা কৰক',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'হৰ্ণবিল উৎসৱ ↔ নাগালেণ্ড, বিহু ↔ অসম, ৰুট ব্ৰীজ ↔ মেঘালয় মিলাওক',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'ষ্ট্ৰুপ পৰীক্ষা — শব্দটো নহয়, পাঠটোৰ ৰংটোত টিপক (মনোযোগ আৰু বাধা)',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'এন ই আৰ লোক প্ৰবাদ সম্পূৰ্ণ কৰক — "যি বাঁহ বেঁকা হয় সি বেছি শক্তিশালী..."',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'K_Z_R_NGA, SH_LL_NG ত হেৰুওৱা আখৰ পূৰণ কৰক — এন ই আৰ ঠাইৰ নাম পুনৰুদ্ধাৰ',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'হাইলাইট কৰা হস্ততাঁত বয়ন কোষবোৰ মনত ৰাখক, তাৰ পিছত স্মৃতিৰ পৰা পুনৰাবৃত্তি কৰক',
  },

  mni: {
    'Across 8 cognitive domains': 'কোগনিটিভ ডোমেইন ৮গী মরমদা',
    'Great engagement!': 'ফজবা থৌরাং!',
    'Try more games!': 'অতোপ্পা থৌরাং ৱাখল্লো!',
    'AI Difficulty Level': 'AI ৱাখল্লোনগী লেভেল',
    'Level': 'লেভেল',
    'Auto-adapted to your skill': 'মশা মশাগী থৌরাংদা শেম্বা',
    'Music Therapy': 'ৱারোল ইশৈ',
    'Family Faces': 'ইমুংগী মশকশিং',
    'Odd One Out': 'তোপ তোপ্পা খন্বা',
    'Therapy': 'ইশৈ',
    'Personal': 'ইশাগী',
    'Categorization': 'মখল খাইদোকপা',
    'Memory': 'ৱাখল',
    'Auditory Memory': 'তাবগী ৱাখল',
    'Executive Fn': 'থবক তৌবা',
    'Numerical': 'নম্বর',
    'Semantic Memory': 'অৰ্থগী ৱাখল',
    'Attention': 'পুক্নিং',
    'Language': 'লোন',
    'Lexical': 'ৱাহৈ',
    'Visuospatial': 'উবগী ৱাখল',
    'Easy': 'লাইবা',
    'Medium': 'মচিন',
    'Hard': 'অরূবা',
    'Calming algorithmic NER folk melodies for sundowning relief': 'মতমগী মতুং ইন্না NER ৱারোল ইশৈ',
    'Recognize your family members and loved ones from uploaded photos': 'ইমুং মনুংগী মশকশিং খংদোকপা',
    'Find the item that does not belong in the category': 'তোপ তোপ্পা খন্বা',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'NER ল্যান্ডমার্ক কার্ডশিং খংদোকপা',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'ইশৈগী ৱারোলশিং খংদোকপা',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'অয়ুক্কী থবকশিং শেম্বা',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'চানবা অমদি খুৎশৈবা খন্বা',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'নম্বরশিং খংদোকপা',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'কুম্মৈশিং অমদি রাজ্য খংদোকপা',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'রং খংদোকপা',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'ৱাখল জ্ঞান খংদোকপা',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'মফমগী মিং খংদোকপা',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'ফিগার হন্থবা',
 // Manipuri (Meitei Mayek transliterated)
    appName: 'কোগ্নিকেয়ার NER',
    tagline: 'মেমোরি কেয়ার প্লাটফর্ম',
    patient: 'অনাবা',
    caregiver: 'শেন্নবা',
    games: 'ৱাখল্লোনগী থৌরাং',
    reminders: 'নুমীদাং চিংনবা',
    dashboard: 'ডেশবোর্ড',
    patients: 'অনাবা শেম্নৈ',
    alerts: 'লমজিং',
    settings: 'শেৎপা',
    back: 'হন্দোক্লো',
    next: 'মতমদা',
    play: 'ৱাখল্লো',
    score: 'নম্বর',
    level: 'লেভেল',
    correct: 'ফজবা! অদু ফৈ!',
    tryAgain: 'অমুক হান্না হোৎননবীরো।',
    gameComplete: 'মরম থোকপা! নং ওইখি!',
    medicine: 'লায়েং চাবগী পুক্নিং থৌগৎপা',
    water: 'ঈশিং থক্কো',
    exercise: 'হেন্না নৌপা',
    appointment: 'ডাক্তর লৈবা',
    morning: 'অয়ুক',
    afternoon: 'নুংথিল',
    evening: 'নুংশিৎ',
    selectLanguage: 'লোন',
    selectTheme: 'থিম',
    switchPortal: 'পোর্টাল থুনা',
    patientPortal: 'অনাবা পোর্টাল',
    caregiverPortal: 'শেন্নবা পোর্টাল',
    gamesSubtitle: 'অমা থেংনবা য়ারো। থৌরাং অসিনা নংগী মতম অমত্তা ফিৎনবা লৌ।',
    readAloud: 'হায়রো',
    gamesAvailable: 'থৌরাং শেম্নৈ',
    gamesPlayed: 'থৌরাং ৱাখল্লে',
    overallAccuracy: 'অরোইবা নম্বর',
    welcome: 'কোগ্নিকেয়ার NER-দা য়াম্না পোথোকপা',
    heroSubtitle: 'NER রেগিওন থা অনাবা অমিওৎপা লৌমীশিংগীদমক AI-গী মায়োক্না ৱাখল্লোন।',
    enterPatient: 'অনাবা পোর্টালদা পুরো',
    enterCaregiver: 'শেন্নবা পোর্টালদা পুরো',
    morningMedicine: 'অয়ুকগী লায়েং',
    drinkWater: 'ঈশিং থক্কো',
    morningWalk: 'অয়ুকগী হেন্না',
    brainGames: 'মতম থৌরাং খরা',
    lunchMedicine: 'নুংথিলগী লায়েং',
    afternoonRest: 'নুংথিলগী থম্মোন',
    teaSnack: 'চাহ অমদি খানা',
    eveningWalk: 'নুংশিৎকী হেন্না',
    doctorAppointment: 'ডাক্তর লৈবা',
    eveningMedicine: 'নুংশিৎকী লায়েং',
    musicTherapy: 'ৱারোল ইশৈ',
    sleepPrep: 'থমনবগী তৈয়ারী',
    morningMedicineDetail: 'লায়েং য়াম্না থেংনবা ঈশিংনা থক্কো',
    drinkWaterDetail: 'ঈশিং অমা থক্কো - শরীর লৈবা',
    morningWalkDetail: '১৫ মিনিট নুংঙাইবা হেন্না হোৎনরো',
    brainGamesDetail: '২-৩টা থৌরাং খরা ৱাখল্লো',
    lunchMedicineDetail: 'নুংথিলগী খানার মতুংদা লায়েং থক্কো',
    afternoonRestDetail: '৩০ মিনিট থমম্মোন হোৎনরো',
    teaSnackDetail: 'চাহ অমদি লৈবা খানা',
    eveningWalkDetail: 'নুংশিৎতা হেন্না হোৎনরো',
    doctorAppointmentDetail: 'ডাক্তরনা টেলিফোন্দা লৈবা',
    eveningMedicineDetail: 'ইথৌরগীদমক লায়েং থক্কো',
    musicTherapyDetail: 'NER ৱারোল ইশৈ হায়রো',
    sleepPrepDetail: 'থোকচিল অমদি লায়েং থমনবা তৈয়ারী',
    todayProgress: 'নুপীদা অগ্রগতি',
    currentTime: 'মতম অসিদা',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    medicinesLabel: 'লায়েং',
    hydrationLabel: 'ঈশিং',
    allTaken: 'ফংলে!',
    wellHydrated: 'ঈশিং য়াম্নিংবা!',
    drinkMoreWater: 'ঈশিং য়াম্না থক্কো',
    memoryMatch: 'ল্যান্ডমার্ক হন্থবা',
    melodyMemory: 'ৱারোল হন্থবা',
    dailyRoutine: 'নুপীদা হোৎনবা',
    marketSorting: 'বজার সেৎপা',
    patternReplication: 'ফিগার হন্থবা',
    wordCompletion: 'ৱার্ড হন্থবা',
    numberPatterns: 'নম্বর ফিগার',
    culturalConnections: 'থৌৱারোল সংযোগ',
    colourWord: 'রং অমদি ৱার্ড',
    proverbCompletion: 'ৱাখল জ্ঞান',
    oddOneOut: 'তোপ তোপ্পা খন্বা',
    familyFaces: 'ইমুংগী মশকশিং',
    addReminder: 'কাষ্টম রিমাইন্ডার হাপচিনবা',
    addReminderBtn: '+ রিমাইন্ডার হাপচিনবা',
    saveReminder: 'রিমাইন্ডার সেভ তৌবা',
    cancel: 'কেন্সেল তৌবা',
    timeLabel: 'মতম',
    titleLabel: 'মিংথোল',
    detailLabel: 'অকুপ্পা ৱারোল',
  },

  hi: {
    'Caregiver Dashboard': 'देखभालकर्ता डैशबोर्ड',
    'Monitor cognitive performance, track engagement trends, and receive AI-powered clinical insights.': 'संज्ञानात्मक प्रदर्शन की निगरानी करें, रुझानों को ट्रैक करें और AI-संचालित नैदानिक अंतर्दृष्टि प्राप्त करें।',
    'Cognitive Wellness Index': 'संज्ञानात्मक कल्याण सूचकांक',
    'Out of 100': '100 में से',
    'AI Multi-Signal Attribution': 'AI मल्टी-सिग्नल एट्रिब्यूशन',
    'Game Performance': 'खेल प्रदर्शन',
    'Emotional Stability': 'भावनात्मक स्थिरता',
    'Speech Fluency Biomarker': 'भाषण प्रवाह बायोमार्कर',
    'Sessions This Week': 'इस सप्ताह के सत्र',
    'Average Accuracy': 'औसत सटीकता',
    'Avg Response Time': 'औसत प्रतिक्रिया समय',
    'Active Streak': 'सक्रिय लकीर',
    'Reminders Completed': 'अनुस्मारक पूर्ण',
    'Caregiver Wellbeing': 'देखभालकर्ता कल्याण',
    'Sundowning Pattern Detected': 'सनडाउनिंग पैटर्न का पता चला',
    'CRITICAL': 'गंभीर',
    'AI Recommendation:': 'AI सिफारिश:',
    '7-Day Cognitive Performance': '7-दिन का संज्ञानात्मक प्रदर्शन',
    'Accuracy & response time trends': 'सटीकता और प्रतिक्रिया समय के रुझान',
    'Cognitive Digital Twin': 'संज्ञानात्मक डिजिटल ट्विन',
    'Radar mapping of 6 brain domains (CST)': '6 मस्तिष्क डोमेन का रडार मैपिंग',
    'Patient Mood Trend': 'रोगी के मूड का रुझान',
    'Self-reported pre-session emotional state': 'सत्र-पूर्व भावनात्मक स्थिति',
    'Conversational Cognitive Signal': 'संवादात्मक संज्ञानात्मक संकेत',
    'Speech fluency biomarker from Smriti Phone': 'स्मृति फोन से भाषण प्रवाह बायोमार्कर',
    'Recent Game Sessions': 'हाल के खेल सत्र',
    'Detailed session history with accuracy tracking': 'सटीकता ट्रैकिंग के साथ विस्तृत सत्र इतिहास',
    'Live Analysis': 'लाइव विश्लेषण',
    'Accuracy': 'सटीकता',
    'Performance': 'प्रदर्शन',
    'Time': 'समय',
    'Game Exercise': 'खेल अभ्यास',

    'Across 8 cognitive domains': '8 संज्ञानात्मक डोमेन में',
    'Great engagement!': 'शानदार जुड़ाव!',
    'Try more games!': 'और खेल आजमाएं!',
    'AI Difficulty Level': 'AI कठिनाई स्तर',
    'Level': 'स्तर',
    'Auto-adapted to your skill': 'आपके कौशल के अनुसार स्वतः अनुकूलित',
    'Music Therapy': 'संगीत चिकित्सा',
    'Family Faces': 'पारिवारिक चेहरे',
    'Odd One Out': 'विषम को पहचानें',
    'Therapy': 'चिकित्सा',
    'Personal': 'व्यक्तिगत',
    'Categorization': 'वर्गीकरण',
    'Memory': 'स्मृति',
    'Auditory Memory': 'श्रवण स्मृति',
    'Executive Fn': 'कार्यकारी कार्य',
    'Numerical': 'संख्यात्मक',
    'Semantic Memory': 'अर्थपूर्ण स्मृति',
    'Attention': 'ध्यान',
    'Language': 'भाषा',
    'Lexical': 'शाब्दिक',
    'Visuospatial': 'दृश्य-स्थानिक',
    'Easy': 'आसान',
    'Medium': 'मध्यम',
    'Hard': 'कठिन',
    'Calming algorithmic NER folk melodies for sundowning relief': 'सूर्यास्त के समय राहत के लिए शांत NER लोक धुनें',
    'Recognize your family members and loved ones from uploaded photos': 'अपलोड की गई तस्वीरों से अपने परिवार के सदस्यों और प्रियजनों को पहचानें',
    'Find the item that does not belong in the category': 'उस आइटम को खोजें जो श्रेणी से संबंधित नहीं है',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'NER लैंडमार्क कार्ड का मिलान करें — काजीरंगा, तवांग और अन्य के साथ दृश्य-स्थानिक स्मृति को प्रशिक्षित करता है',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'ऑफ़लाइन संश्लेषित बिहू ढोल, पेपा, पुंग और बांसुरी के अनुक्रम याद करें',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'सुबह की चाय बनाने, आत्म-देखभाल और बगीचे की दिनचर्या को सही क्रम में व्यवस्थित करें',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'भुत जोलोकिया, बांस के अंकुर, मेखेला चादर को भोजन बनाम हस्तशिल्प टोकरियों में छाँटें',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'अनुक्रमों में लापता संख्याएँ खोजें — चाय की टोकरियाँ, पान के गुच्छे, ₹5 के नोट गिनें',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'हॉर्नबिल महोत्सव ↔ नागालैंड, बिहू ↔ असम, रूट ब्रिज ↔ मेघालय का मिलान करें',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'स्ट्रूप परीक्षण — पाठ के रंग पर टैप करें, शब्द पर नहीं (ध्यान और निषेध)',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'NER लोक कहावतों को पूरा करें — "जो बांस झुकता है वह अधिक मजबूत होता है..."',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'K_Z_R_NGA, SH_LL_NG में लापता अक्षर भरें — NER स्थान के नाम की रिकवरी',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'हाइलाइट किए गए हथकरघा बुनाई कोशिकाओं को याद करें, फिर स्मृति से दोहराएं',
 // Hindi
    appName: 'कॉग्निकेयर NER',
    tagline: 'स्मृति देखभाल मंच',
    patient: 'रोगी',
    caregiver: 'देखभालकर्ता',
    games: 'संज्ञानात्मक खेल',
    reminders: 'दैनिक अनुस्मारक',
    dashboard: 'डैशबोर्ड',
    patients: 'रोगी प्रोफाइल',
    alerts: 'सतर्कताएँ और अंतर्दृष्टि',
    settings: 'सेटिंग',
    back: 'वापस',
    next: 'अगला',
    play: 'खेलें',
    score: 'अंक',
    level: 'स्तर',
    correct: 'बहुत बढ़िया! सही उत्तर!',
    tryAgain: 'लगभग हो गया! फिर कोशिश करें।',
    gameComplete: 'शानदार! आपने अभ्यास पूरा किया!',
    medicine: 'दवाई याद',
    water: 'पानी पियें',
    exercise: 'हल्की कसरत',
    appointment: 'डॉक्टर अपॉइंटमेंट',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    selectLanguage: 'भाषा',
    selectTheme: 'थीम',
    switchPortal: 'पोर्टल बदलें',
    patientPortal: 'रोगी पोर्टल',
    caregiverPortal: 'देखभालकर्ता पोर्टल',
    gamesSubtitle: 'एक अभ्यास चुनें। प्रत्येक खेल आपके दिमाग के एक अलग हिस्से को प्रशिक्षित करता है।',
    readAloud: 'जोर से पढ़ें',
    gamesAvailable: 'खेल उपलब्ध',
    gamesPlayed: 'खेले गए खेल',
    overallAccuracy: 'कुल सटीकता',
    welcome: 'कॉग्निकेयर NER में आपका स्वागत है',
    heroSubtitle: 'उत्तर-पूर्वी भारत के बुजुर्ग डिमेंशिया रोगियों के लिए AI-संचालित संज्ञानात्मक खेल और स्मृति सहायता।',
    enterPatient: 'रोगी पोर्टल में प्रवेश करें',
    enterCaregiver: 'देखभालकर्ता पोर्टल में प्रवेश करें',
    morningMedicine: 'सुबह की दवाई',
    drinkWater: 'पानी पियें',
    morningWalk: 'सुबह की सैर',
    brainGames: 'दिमागी खेल का समय',
    lunchMedicine: 'दोपहर की दवाई',
    afternoonRest: 'आराम और झपकी',
    teaSnack: 'चाय और नाश्ता',
    eveningWalk: 'शाम की सैर',
    doctorAppointment: 'डॉक्टर अपॉइंटमेंट',
    eveningMedicine: 'शाम की दवाई',
    musicTherapy: 'संगीत चिकित्सा',
    sleepPrep: 'नींद की तैयारी',
    morningMedicineDetail: 'गर्म पानी के साथ सुबह की गोलियाँ लें',
    drinkWaterDetail: 'एक गिलास गर्म पानी पियें — हाइड्रेटेड रहें',
    morningWalkDetail: 'बगीचे में 15 मिनट की हल्की सैर',
    brainGamesDetail: 'मानसिक उत्तेजना के लिए 2-3 खेल खेलें',
    lunchMedicineDetail: 'दोपहर के खाने के बाद दवाई लें',
    afternoonRestDetail: 'ठीक होने के लिए 30 मिनट का आराम',
    teaSnackDetail: 'असम की चाय और हल्के नाश्ते का आनंद लें',
    eveningWalkDetail: 'ताज़ी हवा के लिए छोटी शाम की सैर',
    doctorAppointmentDetail: 'न्यूरोलॉजिस्ट के साथ साप्ताहिक टेली-परामर्श',
    eveningMedicineDetail: 'रात के खाने के साथ शाम की दवाई लें',
    musicTherapyDetail: 'शांत NER लोक संगीत सुनें',
    sleepPrepDetail: 'रोशनी कम करें और आरामदायक नींद की तैयारी करें',
    todayProgress: 'आज की दैनिक प्रगति',
    currentTime: 'वर्तमान समय',
    overallProgress: 'कुल प्रगति',
    medicinesLabel: 'दवाइयाँ',
    hydrationLabel: 'जलयोजन',
    allTaken: 'सब ले लिया!',
    wellHydrated: 'अच्छी तरह हाइड्रेटेड!',
    drinkMoreWater: 'और पानी पियें',
    memoryMatch: 'लैंडमार्क स्मृति',
    melodyMemory: 'धुन स्मृति',
    dailyRoutine: 'दैनिक दिनचर्या',
    marketSorting: 'बाज़ार छँटाई',
    patternReplication: 'बुनाई पैटर्न',
    wordCompletion: 'शब्द स्मरण',
    numberPatterns: 'संख्या पैटर्न',
    culturalConnections: 'सांस्कृतिक संबंध',
    colourWord: 'रंग और शब्द',
    proverbCompletion: 'कहावत ज्ञान',
    oddOneOut: 'विषम चुनें',
    familyFaces: 'परिवार के चेहरे',
    addReminder: 'कस्टम अनुस्मारक जोड़ें',
    addReminderBtn: '+ अनुस्मारक जोड़ें',
    saveReminder: 'अनुस्मारक सहेजें',
    cancel: 'रद्द करें',
    timeLabel: 'समय',
    titleLabel: 'शीर्षक',
    detailLabel: 'विवरण',
  },

  bn: {
    'Across 8 cognitive domains': '৮টি জ্ঞানীয় ডোমেইন জুড়ে',
    'Great engagement!': 'দারুণ অংশগ্রহণ!',
    'Try more games!': 'আরও খেলা চেষ্টা করুন!',
    'AI Difficulty Level': 'AI অসুবিধার স্তর',
    'Level': 'স্তর',
    'Auto-adapted to your skill': 'আপনার দক্ষতার সাথে স্বয়ংক্রিয়ভাবে খাপ খাইয়ে নেওয়া',
    'Music Therapy': 'মিউজিক থেরাপি',
    'Family Faces': 'পরিবারের মুখ',
    'Odd One Out': 'অড ওয়ান আউট',
    'Therapy': 'থেরাপি',
    'Personal': 'ব্যক্তিগত',
    'Categorization': 'শ্রেণীকরণ',
    'Memory': 'স্মৃতি',
    'Auditory Memory': 'শ্রবণ স্মৃতি',
    'Executive Fn': 'নির্বাহী কাজ',
    'Numerical': 'সাংখ্যিক',
    'Semantic Memory': 'অর্থগত স্মৃতি',
    'Attention': 'মনোযোগ',
    'Language': 'ভাষা',
    'Lexical': 'আভিধানিক',
    'Visuospatial': 'দৃশ্য-স্থানিক',
    'Easy': 'সহজ',
    'Medium': 'মাঝারি',
    'Hard': 'কঠিন',
    'Calming algorithmic NER folk melodies for sundowning relief': 'সূর্যাস্তের সময় স্বস্তির জন্য শান্ত এন ই আর লোক সুর',
    'Recognize your family members and loved ones from uploaded photos': 'আপলোড করা ছবি থেকে আপনার পরিবারের সদস্য এবং প্রিয়জনদের চিনুন',
    'Find the item that does not belong in the category': 'যেই আইটেমটি শ্রেণীর অন্তর্গত নয় তা খুঁজুন',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'এন ই আর ল্যান্ডমার্ক কার্ড মিলান — কাজিরাঙ্গা, তাওয়াং এবং আরও অনেক কিছুর সাথে দৃশ্য-স্থানিক স্মৃতি প্রশিক্ষণ দেয়',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'অফলাইনে সংশ্লেষিত বিহু ঢোল, পেপা, পুং এবং বাঁশির ক্রম মনে করুন',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'সকালের চা বানানো, নিজের যত্ন নেওয়া এবং বাগানের কাজগুলি সঠিক ক্রমে সাজান',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'ভুত জলোকিয়া, বাঁশের অঙ্কুর, মেখেলা চাদরকে খাবার বনাম হস্তশিল্পের ঝুড়িতে সাজান',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'ক্রমগুলিতে হারিয়ে যাওয়া সংখ্যাগুলি খুঁজুন — চায়ের ঝুড়ি, পানের গুচ্ছ, ₹৫ নোট গণনা করুন',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'হর্নবিল উৎসব ↔ নাগাল্যান্ড, বিহু ↔ আসাম, রুট ব্রিজ ↔ মেঘালয় মিলান',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'স্ট্রুপ পরীক্ষা — শব্দের নয়, পাঠ্যের রঙে আলতো চাপুন (মনোযোগ এবং বাধা)',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'এন ই আর লোক প্রবাদগুলি সম্পূর্ণ করুন — "যে বাঁশ বাঁকে তা আরও শক্তিশালী..."',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'K_Z_R_NGA, SH_LL_NG-এ হারিয়ে যাওয়া অক্ষর পূরণ করুন — এন ই আর জায়গার নাম পুনরুদ্ধার',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'হাইলাইট করা তাঁত বোনা কোষগুলি মুখস্ত করুন, তারপর স্মৃতি থেকে প্রতিলিপি করুন',
 // Bengali
    appName: 'কগ্নিকেয়ার NER',
    tagline: 'স্মৃতি যত্ন মঞ্চ',
    patient: 'রোগী',
    caregiver: 'পরিচর্যাকারী',
    games: 'জ্ঞানমূলক খেলা',
    reminders: 'দৈনিক অনুস্মারক',
    dashboard: 'ড্যাশবোর্ড',
    patients: 'রোগীর প্রোফাইল',
    alerts: 'সতর্কতা ও অন্তর্দৃষ্টি',
    settings: 'সেটিং',
    back: 'পিছনে',
    next: 'পরবর্তী',
    play: 'খেলুন',
    score: 'স্কোর',
    level: 'স্তর',
    correct: 'চমৎকার! সঠিক উত্তর!',
    tryAgain: 'প্রায় হয়ে গেছে! আবার চেষ্টা করুন।',
    gameComplete: 'অসাধারণ! আপনি অনুশীলন সম্পন্ন করলেন!',
    medicine: 'ওষুধের অনুস্মারক',
    water: 'জল পান করুন',
    exercise: 'হালকা ব্যায়াম',
    appointment: 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
    morning: 'সকাল',
    afternoon: 'দুপুর',
    evening: 'সন্ধ্যা',
    selectLanguage: 'ভাষা',
    selectTheme: 'থিম',
    switchPortal: 'পোর্টাল বদলান',
    patientPortal: 'রোগী পোর্টাল',
    caregiverPortal: 'পরিচর্যাকারী পোর্টাল',
    gamesSubtitle: 'একটি অনুশীলন বেছে নিন। প্রতিটি খেলা আপনার মনের আলাদা অংশকে প্রশিক্ষণ দেয়।',
    readAloud: 'জোরে পড়ুন',
    gamesAvailable: 'খেলা উপলব্ধ',
    gamesPlayed: 'খেলা খেলেছেন',
    overallAccuracy: 'সামগ্রিক নির্ভুলতা',
    welcome: 'কগ্নিকেয়ার NER-এ স্বাগতম',
    heroSubtitle: 'উত্তর-পূর্ব ভারতের বৃদ্ধ ডিমেনশিয়া রোগীদের জন্য AI-চালিত জ্ঞানমূলক খেলা এবং স্মৃতি সহায়তা।',
    enterPatient: 'রোগী পোর্টালে প্রবেশ করুন',
    enterCaregiver: 'পরিচর্যাকারী পোর্টালে প্রবেশ করুন',
    morningMedicine: 'সকালের ওষুধ',
    drinkWater: 'জল পান করুন',
    morningWalk: 'সকালের হাঁটা',
    brainGames: 'মস্তিষ্কের খেলার সময়',
    lunchMedicine: 'দুপুরের ওষুধ',
    afternoonRest: 'বিশ্রাম ও ঘুম',
    teaSnack: 'চা ও নাস্তা',
    eveningWalk: 'সন্ধ্যার হাঁটা',
    doctorAppointment: 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
    eveningMedicine: 'সন্ধ্যার ওষুধ',
    musicTherapy: 'সংগীত থেরাপি',
    sleepPrep: 'ঘুমের প্রস্তুতি',
    morningMedicineDetail: 'গরম জল দিয়ে সকালের বড়ি নিন',
    drinkWaterDetail: 'এক গ্লাস গরম জল পান করুন - হাইড্রেটেড থাকুন',
    morningWalkDetail: 'বাগানে ১৫ মিনিট সহজে হাঁটুন',
    brainGamesDetail: 'মানসিক উদ্দীপনার জন্য ২-৩টি খেলা খেলুন',
    lunchMedicineDetail: 'দুপুরের খাবারের পরে ওষুধ নিন',
    afternoonRestDetail: 'সুস্থতার জন্য সংক্ষিপ্ত ৩০ মিনিটের বিশ্রাম',
    teaSnackDetail: 'আসাম চা এবং হালকা স্বাস্থ্যকর নাস্তা উপভোগ করুন',
    eveningWalkDetail: 'তাজা বাতাসের জন্য সংক্ষিপ্ত সন্ধ্যার হাঁটা',
    doctorAppointmentDetail: 'নিউরোলজিস্টের সাথে সাপ্তাহিক টেলি-পরামর্শ',
    eveningMedicineDetail: 'রাতের খাবারের সাথে সন্ধ্যার ওষুধ নিন',
    musicTherapyDetail: 'শান্ত NER লোক সংগীত শুনুন',
    sleepPrepDetail: 'আলো কমান এবং প্রশান্তির ঘুমের জন্য প্রস্তুতি নিন',
    todayProgress: 'আজকের দৈনিক অগ্রগতি',
    currentTime: 'বর্তমান সময়',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    medicinesLabel: 'ওষুধ',
    hydrationLabel: 'জলযোজন',
    allTaken: 'সব নেওয়া হয়েছে!',
    wellHydrated: 'ভালোভাবে হাইড্রেটেড!',
    drinkMoreWater: 'আরও জল পান করুন',
    memoryMatch: 'ল্যান্ডমার্ক স্মৃতি',
    melodyMemory: 'সুর স্মৃতি',
    dailyRoutine: 'দৈনিক রুটিন',
    marketSorting: 'বাজার সাজানো',
    patternReplication: 'বুনন নকশা',
    wordCompletion: 'শব্দ স্মরণ',
    numberPatterns: 'সংখ্যা নকশা',
    culturalConnections: 'সাংস্কৃতিক সংযোগ',
    colourWord: 'রঙ ও শব্দ',
    proverbCompletion: 'প্রবাদ জ্ঞান',
    oddOneOut: 'অস্বাভাবিকটি বেছে নিন',
    familyFaces: 'পরিবারের মুখগুলি',
    addReminder: 'কাস্টম অনুস্মারক যোগ করুন',
    addReminderBtn: '+ অনুস্মারক যোগ করুন',
    saveReminder: 'অনুস্মারক সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    timeLabel: 'সময়',
    titleLabel: 'শিরোনাম',
    detailLabel: 'বিবরণ',
  },

  kha: {
    'Across 8 cognitive domains': 'Across 8 cognitive domains',
    'Great engagement!': 'Kynmaw bha!',
    'Try more games!': 'Lehkai shuh shuh!',
    'AI Difficulty Level': 'AI Level ban Jymma',
    'Level': 'Level',
    'Auto-adapted to your skill': 'Auto-adapted sha ka jinglah jong phi',
    'Music Therapy': 'Rwai Therapy',
    'Family Faces': 'Dur Jong Kiba Hajan',
    'Odd One Out': 'Kaba Lait',
    'Therapy': 'Therapy',
    'Personal': 'Shimet',
    'Categorization': 'Pyniakhlad',
    'Memory': 'Kynmaw',
    'Auditory Memory': 'Kynmaw Sngew',
    'Executive Fn': 'Kam',
    'Numerical': 'Dak',
    'Semantic Memory': 'Kynmaw Mut',
    'Attention': 'Phikir',
    'Language': 'Ktien',
    'Lexical': 'Ktien',
    'Visuospatial': 'Iohi',
    'Easy': 'Jem',
    'Medium': 'Pdeng',
    'Hard': 'Eh',
    'Calming algorithmic NER folk melodies for sundowning relief': 'Calming NER folk melodies',
    'Recognize your family members and loved ones from uploaded photos': 'Tip ia kiba hajan',
    'Find the item that does not belong in the category': 'Wad ia kaba lait',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'Match NER landmark cards',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'Kynmaw sur Bihu, Pepa, Besli',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'Pynbeit ia ki kam mynstep',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'Pyniakhlad jingbam bad tiar',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'Wad ia ki dak kiba jah',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'Match Hornbill, Bihu, Root Bridges',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'Tap the COLOUR',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'Complete NER folk proverbs',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'Pyndap dak kiba jah',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'Kynmaw rukom thain',
 // Khasi
    appName: 'CogniCare NER',
    tagline: 'Jingïaphaw jingmut platform',
    patient: 'U bynriew uba ïap',
    caregiver: 'U nongpynïaid',
    games: 'Ki khynraw jingmut',
    reminders: 'Ki jingpynmaw sngi',
    dashboard: 'Dashboard',
    patients: 'Ki profile ki bynriew',
    alerts: 'Ki jingpynmaw balang',
    settings: 'Ki setting',
    back: 'Shakhmat',
    next: 'Kynmaw',
    play: 'Ia khynraw',
    score: 'Score',
    level: 'Level',
    correct: 'Babha! Dei bha!',
    tryAgain: 'Sngewbha beit ha ka jingthoh!',
    gameComplete: 'Babha khawp! Ngi pynmih la!',
    medicine: 'Ka jingpynïaid dawai',
    water: 'Dih um',
    exercise: 'Jingwang rit',
    appointment: 'Appointment doctor',
    morning: 'Sngi pyllong',
    afternoon: 'Sngi rangbah',
    evening: 'Sngi shibun',
    selectLanguage: 'Ka ktien',
    selectTheme: 'Theme',
    switchPortal: 'Leit sha portal pat',
    patientPortal: 'Portal ki bynriew',
    caregiverPortal: 'Portal ki nongpynïaid',
    gamesSubtitle: 'Tip ia ka khynraw bait. Ki khynraw kynmaw pynïaid ki poïaid ki mih kit.',
    readAloud: 'Pynïaid mariang',
    gamesAvailable: 'Ki khynraw don',
    gamesPlayed: 'Ki khynraw la ia khynraw',
    overallAccuracy: 'Jingthoh bha pyrthei',
    welcome: 'Wan sha CogniCare NER',
    heroSubtitle: 'AI jingïaid ka jingkhynraw jingmut bad jingphah jingmut sha ki khynnah ïaid ha NER.',
    enterPatient: 'Leit sha portal ki bynriew',
    enterCaregiver: 'Leit sha portal ki nongpynïaid',
    morningMedicine: 'Dawai sngi pyllong',
    drinkWater: 'Dih um',
    morningWalk: 'Jingwang sngi pyllong',
    brainGames: 'Myntoi khynraw jingmut',
    lunchMedicine: 'Dawai ba ngi bam khana',
    afternoonRest: 'Jingïoh bad jingkhuid',
    teaSnack: 'Sha bad khana rit',
    eveningWalk: 'Jingwang sngi shibun',
    doctorAppointment: 'Appointment doctor',
    eveningMedicine: 'Dawai sngi shibun',
    musicTherapy: 'Jingtip musiQ NER',
    sleepPrep: 'Jingbeit sha jingkhuid',
    morningMedicineDetail: 'Ioh dawai kylliang bad um myntoi',
    drinkWaterDetail: 'Dih um amet - ioh shaïing',
    morningWalkDetail: '15 myntoi jingwang rit ha lum',
    brainGamesDetail: '2-3 ki khynraw jingmut',
    lunchMedicineDetail: 'Ioh dawai ïoh la khana sngi rangbah',
    afternoonRestDetail: '30 myntoi jingïoh ka jingbeit',
    teaSnackDetail: 'Tip sha ba sngewïoh',
    eveningWalkDetail: 'Jingwang rit ha sngi shibun',
    doctorAppointmentDetail: 'Tele-jaied ba doctor tymmen',
    eveningMedicineDetail: 'Ioh dawai ïoh la bam khana khynnah',
    musicTherapyDetail: 'Tip musiQ NER ba pynsngewbha',
    sleepPrepDetail: 'Pyndap dieng bad ioh shaïing sha jingkhuid',
    todayProgress: 'Ka jingiapbha sngi mynta',
    currentTime: 'Myntoi ngi biang',
    overallProgress: 'Jingïapbha shibun',
    medicinesLabel: 'Ki dawai',
    hydrationLabel: 'Ka um',
    allTaken: 'Ioh la katno!',
    wellHydrated: 'Ka um bha!',
    drinkMoreWater: 'Dih um yot',
    memoryMatch: 'Jingmut ki landmark',
    melodyMemory: 'Jingmut melody',
    dailyRoutine: 'Jingïaid sngi',
    marketSorting: 'Jingptiah bazaar',
    patternReplication: 'Ki pattern tyngkong',
    wordCompletion: 'Jingmut ki word',
    numberPatterns: 'Ki pattern nambor',
    culturalConnections: 'Ki jingkyndong iing seng',
    colourWord: 'Rang bad word',
    proverbCompletion: 'Ka jingïing iing',
    oddOneOut: 'Jied iaba kong',
    familyFaces: 'Ki dur khmat iing',
    addReminder: 'Thep jingpynmaw thymmai',
    addReminderBtn: '+ Thep jingpynmaw',
    saveReminder: 'Save jingpynmaw',
    cancel: 'Nym thep',
    timeLabel: 'Por',
    titleLabel: 'Kyrteng',
    detailLabel: 'Batai',
  },

  mzo: {
    'Across 8 cognitive domains': 'Cognitive domain 8 ah',
    'Great engagement!': 'I ti tha lutuk!',
    'Try more games!': 'Game dang khel rawh!',
    'AI Difficulty Level': 'AI Harsatna Level',
    'Level': 'Level',
    'Auto-adapted to your skill': 'I thiam dan azirin a in siam rem',
    'Music Therapy': 'Hla Therapy',
    'Family Faces': 'Chhungte Hmel',
    'Odd One Out': 'A Danglam Zawn Chhuah',
    'Therapy': 'Therapy',
    'Personal': 'Mimal',
    'Categorization': 'Thliar Hran',
    'Memory': 'Hriatna',
    'Auditory Memory': 'Ngaihthlak Hriatna',
    'Executive Fn': 'Hnathawh',
    'Numerical': 'Number',
    'Semantic Memory': 'Awmzia Hriatna',
    'Attention': 'Ngaihsakna',
    'Language': 'Tawng',
    'Lexical': 'Thumal',
    'Visuospatial': 'Hmuh theih',
    'Easy': 'Awlsam',
    'Medium': 'Laihawl',
    'Hard': 'Harsa',
    'Calming algorithmic NER folk melodies for sundowning relief': 'Mizo hla hlui te',
    'Recognize your family members and loved ones from uploaded photos': 'I chhungte hmel hre rawh',
    'Find the item that does not belong in the category': 'A danglam zawn chhuah',
    'Match NER landmark cards — trains visual-spatial memory with Kaziranga, Tawang & more': 'NER hmun pawimawh te',
    'Recall sequences of Bihu Dhol, Pepa, Pung & Bamboo Flute synthesized offline': 'Hla ri hriat chhuah',
    'Arrange morning tea brewing, self-care, and garden routines in correct order': 'Zingkar hun hman dan siam rem',
    'Sort Bhut Jolokia, Bamboo Shoots, Mekhela Chador into food vs handicraft baskets': 'Ei tur leh thil siam chhuah thliar hran',
    'Find missing numbers in sequences — counting tea baskets, betel clusters, ₹5 notes': 'Number kim lo zawn chhuah',
    'Match Hornbill Festival ↔ Nagaland, Bihu ↔ Assam, Root Bridges ↔ Meghalaya': 'Kut leh state mil pui',
    'Stroop test — tap the COLOUR of the text, not the word (attention & inhibition)': 'Rawng hmet rawh',
    'Complete NER folk proverbs — "The bamboo that bends is stronger than..."': 'Mizo thufing tih famkim',
    'Fill missing letters in K_Z_R_NGA, SH_LL_NG — NER place name recovery': 'Hmun hming a hawrawp kim lo dah luh',
    'Memorize highlighted handloom weave cells, then replicate from memory': 'Puan tah dan chhinchhiah',
 // Mizo
    appName: 'CogniCare NER',
    tagline: 'Hre thar platform',
    patient: 'Damlo mi',
    caregiver: 'Enkawl tu',
    games: 'Infiamna zirchian',
    reminders: 'Nihna zirtirtu',
    dashboard: 'Dashboard',
    patients: 'Damlo mi profile',
    alerts: 'Thupek',
    settings: 'Setting',
    back: 'Kir leh',
    next: 'Zawn leh',
    play: 'Tui leh',
    score: 'Score',
    level: 'Level',
    correct: 'Tha khawp mai! A dik!',
    tryAgain: 'Tum leh teh ang!',
    gameComplete: 'Ropui tak! I tih zo ta!',
    medicine: 'Damdawi ei tur hriattir',
    water: 'Tui in rawh',
    exercise: 'Zawn tui',
    appointment: 'Doctor appointment',
    morning: 'Zingkar',
    afternoon: 'Chawlhkar',
    evening: 'Thlakthleng',
    selectLanguage: 'Tawng',
    selectTheme: 'Theme',
    switchPortal: 'Portal thlak',
    patientPortal: 'Damlo mi portal',
    caregiverPortal: 'Enkawl tu portal',
    gamesSubtitle: 'Infiamna pakhat thlang rawh. Infiamna tin i lungril a danglam thlang a zir.',
    readAloud: 'Hla sawt pe',
    gamesAvailable: 'Infiamna awm',
    gamesPlayed: 'Infiamna tuah',
    overallAccuracy: 'Score lawmawm',
    welcome: 'CogniCare NER-a i kal chhuah',
    heroSubtitle: 'NER thlengah damlo pa mi upa leh hmasawnna tan AI-in infiamna zirchian.',
    enterPatient: 'Damlo mi portal-a lut',
    enterCaregiver: 'Enkawl tu portal-a lut',
    morningMedicine: 'Zingkar damdawi',
    drinkWater: 'Tui in rawh',
    morningWalk: 'Zingkar zawn',
    brainGames: 'Lungril infiamna',
    lunchMedicine: 'Chawlhkar damdawi',
    afternoonRest: 'Khawlzin leh ninna',
    teaSnack: 'Chhah leh ei bawm',
    eveningWalk: 'Thlakthleng zawn',
    doctorAppointment: 'Doctor appointment',
    eveningMedicine: 'Thlakthleng damdawi',
    musicTherapy: 'Hla NER siamtu',
    sleepPrep: 'Ninna tana beisei',
    morningMedicineDetail: 'Tui zuang nên zingkar damdawi ei rawh',
    drinkWaterDetail: 'Tui hmet khat in rawh — dam rawh',
    morningWalkDetail: '15 minit zingkar a tlang zawn',
    brainGamesDetail: '2–3 lungril infiamna tui ang',
    lunchMedicineDetail: 'Chawlh hnuah damdawi ei rawh',
    afternoonRestDetail: '30 minit khawlzin tih rawh',
    teaSnackDetail: 'Assam chhah leh ei bawm lawm rawh',
    eveningWalkDetail: 'Thlakthleng-ah zawn tui ang',
    doctorAppointmentDetail: 'Damlo doctor tele-appointment khat',
    eveningMedicineDetail: 'Tzan ei tawh zawnin thlakthleng damdawi ei rawh',
    musicTherapyDetail: 'NER hla siamtu zang zawng zawng hre rawh',
    sleepPrepDetail: 'Vawlel leh ninna tana beisei rawh',
    todayProgress: 'Tun thleng progress',
    currentTime: 'Hun thleng',
    overallProgress: 'Lawmawm progress',
    medicinesLabel: 'Damdawi',
    hydrationLabel: 'Tui',
    allTaken: 'Zawh ta!',
    wellHydrated: 'Tui yo ta!',
    drinkMoreWater: 'Tui yo zawng in rawh',
    memoryMatch: 'Landmark hre thar',
    melodyMemory: 'Melody hre thar',
    dailyRoutine: 'Nihin hna',
    marketSorting: 'Bazaar sawisel',
    patternReplication: 'Zo pattern hre thar',
    wordCompletion: 'Thu hre thar',
    numberPatterns: 'Nambur pattern',
    culturalConnections: 'Mimal inthlahna',
    colourWord: 'Rang leh thu',
    proverbCompletion: 'Lehkha thiam',
    oddOneOut: 'A dang thlang chhuak rawh',
    familyFaces: 'Chhungte hmel',
    addReminder: 'Hriattirna thar dah',
    addReminderBtn: '+ Hriattirna dah',
    saveReminder: 'Hriattirna save',
    cancel: 'Sut leh',
    timeLabel: 'Hun',
    titleLabel: 'Thupui',
    detailLabel: 'Sawifiahna',
  },
};

// ============================================================
// MODES & THEMES
// ============================================================
export const MODES = {
  light: {
    name: 'Light',
    emoji: '☀️',
    '--bg-primary': '#F2F7F2',
    '--bg-secondary': '#FFFFFF',
    '--bg-sidebar': '#0B3D3D',
    '--bg-card': '#FFFFFF',
    '--text-primary': '#0A1C11',
    '--text-secondary': '#1F3F2A',
    '--text-muted': '#4A6E55',
    '--border-color': 'rgba(10,80,60,0.12)',
  },
  dark: {
    name: 'Dark',
    emoji: '🌙',
    '--bg-primary': '#0D1117',
    '--bg-secondary': '#161B22',
    '--bg-card': '#1E232B',
    '--bg-card-hover': '#262D35',
    '--bg-accent': '#1A2332',
    '--bg-sidebar': '#090C10',
    '--bg-sidebar-hover': '#0D1117',
    '--text-primary': '#F0F6FC',
    '--text-secondary': '#C9D1D9',
    '--text-muted': '#8B949E',
    '--text-on-dark': '#FFFFFF',
    '--text-on-dark-muted': '#C9D1D9',
    '--border-color': '#30363D',
    '--border-hover': 'rgba(10,126,106,0.5)',
    '--gradient-card': 'linear-gradient(145deg, #1E232B 0%, #161B22 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #0D1117 0%, #161B22 40%, #1A2332 100%)',
    '--gradient-warm': 'linear-gradient(135deg, #1A2332 0%, #161B22 100%)',
    '--shadow-sm': '0 2px 8px rgba(0,0,0,0.2), 0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 20px rgba(0,0,0,0.25), 0 2px 6px rgba(0,0,0,0.2)',
    '--shadow-lg': '0 12px 40px rgba(0,0,0,0.3), 0 4px 12px rgba(0,0,0,0.2)',
    '--shadow-xl': '0 20px 60px rgba(0,0,0,0.35)',
    '--shadow-glow': '0 0 32px rgba(10,126,106,0.3)',
    '--shadow-card-hover': '0 16px 48px rgba(0,0,0,0.3), 0 4px 12px rgba(0,0,0,0.2)',
    '--tooltip-bg': '#1E232B',
    '--tooltip-border': '#30363D',
  },
};

export const THEMES = {
  green: {
    name: 'Forest',
    emoji: '🌿',
    '--bg-primary': '#F2F7F2',
    '--bg-sidebar': '#0B3D3D',
    '--accent-teal': '#0A7E6A',
    '--accent-green': '#1D9B5F',
    '--gradient-primary': 'linear-gradient(135deg, #0A7E6A 0%, #1D9B5F 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #E8F8F0 0%, #F5EFE6 40%, #E4F5E9 100%)',
    '--accent-teal-light': 'rgba(10,126,106,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(10,126,106,0.12) 0%, transparent 70%)',
  },
  blue: {
    name: 'Ocean',
    emoji: '🌊',
    '--bg-primary': '#F0F4FF',
    '--bg-sidebar': '#1A2A4A',
    '--accent-teal': '#1B66C9',
    '--accent-green': '#0D8FA4',
    '--gradient-primary': 'linear-gradient(135deg, #1B66C9 0%, #0D8FA4 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #E8F0FF 0%, #F0F8FF 40%, #E0F5FA 100%)',
    '--accent-teal-light': 'rgba(27,102,201,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(27,102,201,0.12) 0%, transparent 70%)',
  },
  purple: {
    name: 'Twilight',
    emoji: '🌸',
    '--bg-primary': '#F6F2FF',
    '--bg-sidebar': '#2D1B4E',
    '--accent-teal': '#7C3AED',
    '--accent-green': '#9D44DE',
    '--gradient-primary': 'linear-gradient(135deg, #7C3AED 0%, #9D44DE 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #F3EEFF 0%, #FFF0F9 40%, #EDE8FF 100%)',
    '--accent-teal-light': 'rgba(124,58,237,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(124,58,237,0.12) 0%, transparent 70%)',
  },
  amber: {
    name: 'Warm',
    emoji: '🌻',
    '--bg-primary': '#FFFBF0',
    '--bg-sidebar': '#3D2400',
    '--accent-teal': '#C47A00',
    '--accent-green': '#A65D00',
    '--gradient-primary': 'linear-gradient(135deg, #E08B00 0%, #C47A00 100%)',
    '--gradient-hero': 'linear-gradient(160deg, #FFF8E0 0%, #FFF0D6 40%, #FFEBC0 100%)',
    '--accent-teal-light': 'rgba(196,122,0,0.08)',
    '--gradient-glow': 'radial-gradient(circle at 50% 0%, rgba(196,122,0,0.12) 0%, transparent 70%)',
  },
};

const AppContext = createContext();

export function AppProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('cogni_lang') || 'en');
  const [theme, setTheme] = useState(() => localStorage.getItem('cogni_theme') || 'green');
  const [colorMode, setColorMode] = useState(() => localStorage.getItem('cogni_mode') || 'light');
  
  const [difficultyLevel, setDifficultyLevel] = useState(() => {
    return parseInt(localStorage.getItem('cogni_difficulty')) || 2; // Default level 2 (1-5 scale)
  });
  const [gameScores, setGameScores] = useState(() => {
    try { return JSON.parse(localStorage.getItem('cogni_scores') || '[]'); } catch { return []; }
  });
  const [moodLogs, setMoodLogs] = useState(() => {
    try { return JSON.parse(localStorage.getItem('cogni_moods') || '[]'); } catch { return []; }
  });
  
  const [speechLogs, setSpeechLogs] = useState(() => {
    try { 
      const logs = JSON.parse(localStorage.getItem('cogni_speech_logs'));
      if (logs && logs.length > 0) return logs;
      
      // Mock data for demo purposes (Pre-seeding 7 days of speech data)
      return [
        { id: 1, timestamp: new Date(Date.now() - 86400000).toISOString(), duration: 120, wordCount: 95, fillerCount: 5, typeTokenRatio: 0.75, avgWordsPerUtterance: 5.8, fluencyScore: 78 },
        { id: 2, timestamp: new Date(Date.now() - 86400000*2).toISOString(), duration: 180, wordCount: 140, fillerCount: 8, typeTokenRatio: 0.72, avgWordsPerUtterance: 6.1, fluencyScore: 75 },
        { id: 3, timestamp: new Date(Date.now() - 86400000*3).toISOString(), duration: 90, wordCount: 65, fillerCount: 2, typeTokenRatio: 0.81, avgWordsPerUtterance: 6.5, fluencyScore: 82 },
        { id: 4, timestamp: new Date(Date.now() - 86400000*4).toISOString(), duration: 150, wordCount: 110, fillerCount: 12, typeTokenRatio: 0.65, avgWordsPerUtterance: 4.8, fluencyScore: 65 },
        { id: 5, timestamp: new Date(Date.now() - 86400000*5).toISOString(), duration: 200, wordCount: 160, fillerCount: 15, typeTokenRatio: 0.62, avgWordsPerUtterance: 4.5, fluencyScore: 61 }
      ];
    } catch { return []; }
  });

  // Persist language
  useEffect(() => { localStorage.setItem('cogni_lang', language); }, [language]);
  // Persist theme
  useEffect(() => { localStorage.setItem('cogni_theme', theme); }, [theme]);
  // Persist mode
  useEffect(() => { localStorage.setItem('cogni_mode', colorMode); }, [colorMode]);
  // Persist difficulty
  useEffect(() => { localStorage.setItem('cogni_difficulty', difficultyLevel.toString()); }, [difficultyLevel]);
  // Persist scores
  useEffect(() => { localStorage.setItem('cogni_scores', JSON.stringify(gameScores)); }, [gameScores]);
  // Persist moods
  useEffect(() => { localStorage.setItem('cogni_moods', JSON.stringify(moodLogs)); }, [moodLogs]);
  // Persist speech logs
  useEffect(() => { localStorage.setItem('cogni_speech_logs', JSON.stringify(speechLogs)); }, [speechLogs]);

  // --- CIRCADIAN UI ENGINE ---
  const getCircadianMode = () => {
    const hour = new Date().getHours();
    if (hour >= 6 && hour < 10) return 'morning'; // 6 AM - 10 AM
    if (hour >= 10 && hour < 16) return 'day'; // 10 AM - 4 PM
    if (hour >= 16 && hour < 20) return 'evening'; // 4 PM - 8 PM
    return 'night'; // 8 PM - 6 AM
  };

  const [circadianPhase, setCircadianPhase] = useState(getCircadianMode());

  useEffect(() => {
    const interval = setInterval(() => {
      setCircadianPhase(getCircadianMode());
    }, 60000); // Check every minute
    return () => clearInterval(interval);
  }, []);

  // Apply theme CSS variables to :root
  useEffect(() => {
    const root = document.documentElement;
    let modeVars = MODES[colorMode] || MODES.light;
    let themeVars = THEMES[theme] || THEMES.green;
    
    // Circadian Override — only auto-switch if user hasn't manually set dark mode
    // Evening: warm amber theme for sundowning mitigation (if user is on light mode)
    if (circadianPhase === 'evening' && colorMode === 'light') {
      themeVars = THEMES.amber; // Warm tones for sundowning
    }
    // Night: We do NOT force dark mode — we respect user's explicit choice.
    // The circadianPhase state is still exposed so components can react to it.

    // Apply theme (Accents, gradients, and light-mode tinted backgrounds)
    Object.entries(themeVars).forEach(([key, val]) => {
      if (key.startsWith('--')) root.style.setProperty(key, val);
    });

    if (modeVars === MODES.dark) {
      // Overwrite backgrounds/text with dark mode vars
      Object.entries(MODES.dark).forEach(([key, val]) => {
        if (key.startsWith('--')) root.style.setProperty(key, val);
      });
    } else {
      // Apply light mode text/card vars (skipping bg-primary and bg-sidebar so the Theme's tint remains)
      Object.entries(MODES.light).forEach(([key, val]) => {
        if (key !== '--bg-primary' && key !== '--bg-sidebar' && key.startsWith('--')) {
          root.style.setProperty(key, val);
        }
      });
    }
  }, [theme, colorMode, circadianPhase]);

  // Translation function — falls back to English key
  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  const addScore = (gameName, score, maxScore, responseTimeMs) => {
    const accuracy = Math.round((score / maxScore) * 100);
    const entry = {
      id: Date.now(),
      game: gameName,
      score,
      maxScore,
      accuracy,
      responseTimeMs,
      timestamp: new Date().toISOString(),
      language,
      difficultyPlayed: difficultyLevel
    };
    
    setGameScores(prev => {
      const newScores = [entry, ...prev].slice(0, 200);
      
      // --- AI ADAPTIVE DIFFICULTY ENGINE ---
      // Check last 3 games. If consistently high/low, adapt difficulty
      if (newScores.length >= 3) {
        const last3 = newScores.slice(0, 3);
        const avgAccuracy = last3.reduce((sum, g) => sum + g.accuracy, 0) / 3;
        
        if (avgAccuracy >= 85 && difficultyLevel < 5) {
          // Patient is doing too well, increase difficulty
          setDifficultyLevel(d => Math.min(5, d + 1));
        } else if (avgAccuracy < 50 && difficultyLevel > 1) {
          // Patient is struggling, decrease difficulty to reduce frustration
          setDifficultyLevel(d => Math.max(1, d - 1));
        }
      }
      return newScores;
    });
  };

  const addMoodLog = (moodKey) => {
    const entry = {
      id: Date.now(),
      mood: moodKey,
      timestamp: new Date().toISOString()
    };
    setMoodLogs(prev => [entry, ...prev].slice(0, 100));
  };
  
  const addSpeechLog = (logEntry) => {
    setSpeechLogs(prev => [logEntry, ...prev].slice(0, 100));
  };

  const getGameScore = (gameName) => {
    return gameScores.find(g => g.game === gameName) || null;
  };

  return (
    <AppContext.Provider value={{ 
      language, setLanguage, 
      theme, setTheme, 
      colorMode, setColorMode,
      difficultyLevel, setDifficultyLevel,
      t,
      gameScores, addScore, getGameScore,
      moodLogs, addMoodLog,
      speechLogs, addSpeechLog,
      circadianPhase
    }}>
      {children}
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);

export const SUPPORTED_LANGUAGES = [
  { code: 'en',  label: 'English',   native: 'English',     ttsLang: 'en-IN' },
  { code: 'as',  label: 'Assamese',  native: 'অসমীয়া',      ttsLang: 'as-IN' },
  { code: 'mni', label: 'Manipuri',  native: 'মৈতৈলোন্',     ttsLang: 'hi-IN' },
  { code: 'bn',  label: 'Bengali',   native: 'বাংলা',        ttsLang: 'bn-IN' },
  { code: 'kha', label: 'Khasi',     native: 'Khasi',        ttsLang: 'en-IN' },
  { code: 'mzo', label: 'Mizo',      native: 'Mizo ṭawng',   ttsLang: 'en-IN' },
  { code: 'hi',  label: 'Hindi',     native: 'हिन्दी',        ttsLang: 'hi-IN' },
];
